#include "runtime/command_service.h"
#include <iostream>
#include <stdexcept>
using namespace kalara;using namespace architecture;using namespace geometry;using namespace runtime;
namespace {
int checks=0;void check(bool value,const char* message){++checks;if(!value)throw std::runtime_error(message);}
EntityHeader h(const char* id,EntityType type,const char* owner,std::optional<EntityId> layer={}){return {EntityId(id),type,EntityId(owner),std::move(layer),0,0};}
Project fixture(){Project p(EntityId("project"));p.title="Transactions";EntityId floor("floor"),layer("layer");p.entities.emplace(EntityId("building"),Building{h("building",EntityType::building,"project"),"Building",{floor}});p.entities.emplace(floor,Floor{h("floor",EntityType::floor,"building"),"Ground",0,std::nullopt,{EntityId("j1"),EntityId("j2"),EntityId("wall")}});p.entities.emplace(layer,Layer{h("layer",EntityType::layer,"project"),"Walls"});p.entities.emplace(EntityId("j1"),Junction{h("j1",EntityType::junction,"floor",layer),floor,{0,0}});p.entities.emplace(EntityId("j2"),Junction{h("j2",EntityType::junction,"floor",layer),floor,{6000,0}});p.entities.emplace(EntityId("wall"),Wall{h("wall",EntityType::wall,"floor",layer),floor,EntityId("j1"),EntityId("j2"),Length(200),ReferenceLine::center,SideConvention::tangentLeftRight,"generic"});return p;}
Entity moved(const Project& p,const char* id,double x){auto entity=*p.find(EntityId(id));auto& junction=std::get<Junction>(entity);junction.position.x=x;return entity;}
bool success(const CommitResult& result){return std::holds_alternative<CommitSuccess>(result);}
}
int main(){try{
    ProjectStore store(fixture());CommandService service(store,1024*1024);int events=0;CommittedEvent last;service.setEventSink([&](const CommittedEvent& event){++events;last=event;});
    auto base=store.snapshot();auto request=CommandRequest{"junction.move",base->id,base->revision,"Move junction",{{EntityId("j2"),moved(*base,"j2",7500)}},"connected","preserve connected layout"};auto prepared=service.prepare(request);check(std::holds_alternative<ChangePlan>(prepared),"prepare");auto plan=std::get<ChangePlan>(prepared);check(plan.deltas().size()==1&&plan.baseRevision()==0,"immutable plan facts");
    for(int i=0;i<100;++i){auto preview=service.prepare({"drag.preview",base->id,base->revision,"Preview",{{EntityId("j2"),moved(*base,"j2",6001+i)}}});check(std::holds_alternative<ChangePlan>(preview),"draft prepare");}check(store.snapshot()==base&&service.undoCount()==0&&events==0,"100 previews then cancel leaves state/history unchanged");
    auto committed=service.commit(plan);check(success(committed),"commit");check(events==1&&last.changedIds.size()==1,"one event");check(service.undoCount()==1&&!service.redoCount(),"one history entry");check(std::get<Junction>(*store.snapshot()->find(EntityId("j2"))).position.x==7500,"state committed");check(service.dirty(),"dirty after edit");
    check(success(service.undo()),"undo");check(std::get<Junction>(*store.snapshot()->find(EntityId("j2"))).position.x==6000,"undo geometry");check(header(*store.snapshot()->find(EntityId("j2"))).id==EntityId("j2"),"undo ID");check(!service.dirty(),"undo to saved clears dirty");check(events==2,"undo one event");
    check(success(service.redo()),"redo");check(std::get<Junction>(*store.snapshot()->find(EntityId("j2"))).position.x==7500,"redo exact");check(events==3,"redo one event");service.markSaved(store.snapshot()->revision);check(!service.dirty(),"mark saved");
    auto beforeNoop=store.snapshot();auto noopRequest=CommandRequest{"junction.move",beforeNoop->id,beforeNoop->revision,"No move",{{EntityId("j2"),*beforeNoop->find(EntityId("j2"))}}};auto noop=service.commit(std::get<ChangePlan>(service.prepare(noopRequest)));check(std::get<CommitSuccess>(noop).noOp,"no-op result");check(service.undoCount()==1&&events==3&&store.snapshot()->revision==beforeNoop->revision,"no-op no history event revision");
    auto stale=service.commit(plan);check(!success(stale),"stale plan rejected");check(store.snapshot()->revision==beforeNoop->revision,"stale unchanged");
    check(success(service.undo()),"undo before branch");auto redoCount=service.redoCount();auto sameRequest=CommandRequest{"noop",store.snapshot()->id,store.snapshot()->revision,"Noop",{{EntityId("j2"),*store.snapshot()->find(EntityId("j2"))}}};check(std::get<CommitSuccess>(service.commit(std::get<ChangePlan>(service.prepare(sameRequest)))).noOp,"no-op after undo");check(service.redoCount()==redoCount,"no-op retains redo");
    auto branchRequest=CommandRequest{"junction.move",store.snapshot()->id,store.snapshot()->revision,"Branch",{{EntityId("j2"),moved(*store.snapshot(),"j2",7000)}}};check(success(service.commit(std::get<ChangePlan>(service.prepare(branchRequest)))),"branch commit");check(service.redoCount()==0,"effective branch clears redo");
    auto atomicBefore=store.snapshot();std::vector<EntityMutation> five;for(const char* id:{"j1","j2"})five.push_back({EntityId(id),moved(*atomicBefore,id,id==std::string("j1")?100:7100)});auto layer=*atomicBefore->find(EntityId("layer"));std::get<Layer>(layer).name="Changed";five.push_back({EntityId("layer"),layer});auto building=*atomicBefore->find(EntityId("building"));std::get<Building>(building).name="Changed";five.push_back({EntityId("building"),building});auto wall=*atomicBefore->find(EntityId("wall"));std::get<Wall>(wall).thickness=Length(250);five.push_back({EntityId("wall"),wall});auto atomicPlan=std::get<ChangePlan>(service.prepare({"five.change",atomicBefore->id,atomicBefore->revision,"Five changes",five}));const auto historyBefore=service.undoCount();const int eventsBefore=events;service.injectFailureAfter(1);check(!success(service.commit(atomicPlan)),"injected failure");check(semanticContentEqual(*atomicBefore,*store.snapshot())&&atomicBefore->revision==store.snapshot()->revision,"rollback all state");check(service.undoCount()==historyBefore&&events==eventsBefore,"failure no history event");service.injectFailureAfter({});
    int hookCalls=0;service.addDependencyHook([&](const Project&,const std::vector<EntityDelta>& deltas){++hookCalls;return deltas.size()==5?std::vector<Diagnostic>{}:std::vector<Diagnostic>{};});check(success(service.commit(atomicPlan)),"five commit");check(hookCalls==1&&events==eventsBefore+1&&service.undoCount()==historyBefore+1,"dependency hook and atomic event");check(success(service.undo()),"five undo");check(std::get<Junction>(*store.snapshot()->find(EntityId("j1"))).position.x==0&&std::get<Wall>(*store.snapshot()->find(EntityId("wall"))).thickness.mm==200,"five undo exact");
    auto bad=*store.snapshot();(void)bad;auto invalidWall=*store.snapshot()->find(EntityId("wall"));std::get<Wall>(invalidWall).endJunctionId=EntityId("missing");auto invalidPlan=std::get<ChangePlan>(service.prepare({"bad",store.snapshot()->id,store.snapshot()->revision,"Bad",{{EntityId("wall"),invalidWall}}}));auto invalidBefore=store.snapshot();check(!success(service.commit(invalidPlan)),"domain validation rejects");check(invalidBefore->revision==store.snapshot()->revision,"validation atomic");
    service.addDependencyHook([](const Project&,const std::vector<EntityDelta>&){return std::vector<Diagnostic>{{"dependency.blocked",Severity::error,"Dependent entity blocks this change",{},"","Resolve dependency"}};});auto hookPlan=std::get<ChangePlan>(service.prepare({"blocked",store.snapshot()->id,store.snapshot()->revision,"Blocked",{{EntityId("j2"),moved(*store.snapshot(),"j2",7200)}}}));auto hookBefore=store.snapshot();check(!success(service.commit(hookPlan)),"dependency hook blocks atomically");check(hookBefore==store.snapshot(),"blocked hook retains exact snapshot");
    ProjectStore boundedStore(fixture());CommandService bounded(boundedStore,1);for(int i=0;i<3;++i){auto snapshot=boundedStore.snapshot();auto p=std::get<ChangePlan>(bounded.prepare({"move",snapshot->id,snapshot->revision,"Move",{{EntityId("j2"),moved(*snapshot,"j2",6100+i)}}}));check(success(bounded.commit(p)),"bounded commit");}check(bounded.undoCount()==1&&bounded.retainedHistoryBoundary()>0,"oldest complete transactions pruned");
    std::cout<<"commands-v1: "<<checks<<" checks PASS; committed events="<<events<<"; undo restores IDs; injected member failure rolled back\n";return 0;
}catch(const std::exception& error){std::cerr<<"FAIL: "<<error.what()<<'\n';return 1;}}
