#include "editor/input_system.h"
#include <algorithm>
#include <iostream>
#include <numbers>
#include <stdexcept>
using namespace kalara;using namespace architecture;using namespace geometry;using namespace render;using namespace editor;
namespace {
int checks=0;void check(bool value,const char* message){++checks;if(!value)throw std::runtime_error(message);}
EntityHeader h(const char* id,EntityType type,const char* owner,std::optional<EntityId> layer={}){return {EntityId(id),type,EntityId(owner),std::move(layer),0,0};}
Project fixture(){Project p(EntityId("input-project"));p.title="Input";EntityId floor("floor"),visible("visible"),locked("locked"),hidden("hidden");p.entities.emplace(EntityId("building"),Building{h("building",EntityType::building,"input-project"),"Building",{floor}});p.entities.emplace(floor,Floor{h("floor",EntityType::floor,"building"),"Ground",0,std::nullopt,{EntityId("a"),EntityId("b"),EntityId("c"),EntityId("d"),EntityId("e"),EntityId("f"),EntityId("wall-a"),EntityId("wall-b"),EntityId("wall-locked"),EntityId("wall-hidden")}});p.entities.emplace(visible,Layer{h("visible",EntityType::layer,"input-project"),"Visible",true,false,true});p.entities.emplace(locked,Layer{h("locked",EntityType::layer,"input-project"),"Locked",true,true,true});p.entities.emplace(hidden,Layer{h("hidden",EntityType::layer,"input-project"),"Hidden",false,false,true});auto node=[&](const char* id,double x,double y,EntityId layer){p.entities.emplace(EntityId(id),Junction{h(id,EntityType::junction,"floor",layer),floor,{x,y}});};node("a",0,0,visible);node("b",100,0,visible);node("c",0,0,visible);node("d",100,0,visible);node("e",50,-100,locked);node("f",50,100,locked);node("g",0,10,hidden);node("h",100,10,hidden);auto wall=[&](const char* id,const char* a,const char* b,EntityId layer){p.entities.emplace(EntityId(id),Wall{h(id,EntityType::wall,"floor",layer),floor,EntityId(a),EntityId(b),Length(2),ReferenceLine::center,SideConvention::tangentLeftRight,"generic"});};wall("wall-a","a","b",visible);wall("wall-b","c","d",visible);wall("wall-locked","e","f",locked);wall("wall-hidden","g","h",hidden);return p;}
struct ProbeState{int entered=0,cancelled=0,exited=0;bool draft=false;};
class ProbeTool final:public Tool{public:ProbeTool(std::string name,ProbeState& state):name_(std::move(name)),state_(state){}std::string id()const override{return name_;}void enter()override{++state_.entered;}void pointerDown(const PointerEvent&)override{state_.draft=true;}void pointerMove(const PointerEvent&)override{}void pointerUp(const PointerEvent&)override{state_.draft=false;}void key(const KeyEvent&)override{}void cancel()override{++state_.cancelled;state_.draft=false;}void exit()override{++state_.exited;}bool hasDraft()const override{return state_.draft;}std::string name_;ProbeState& state_;};
}
int main(){try{
    ToolController controller;ProbeState firstState,secondState;auto first=std::make_unique<ProbeTool>("first",firstState);controller.activate(std::move(first));check(firstState.entered==1,"tool enter");controller.pointerDown({});check(firstState.draft,"draft starts");controller.focusLost();check(!firstState.draft&&firstState.cancelled==1,"focus loss cancels");controller.pointerDown({});controller.floorChanged();check(firstState.cancelled==2,"floor switch cancels");controller.pointerDown({});auto second=std::make_unique<ProbeTool>("second",secondState);controller.activate(std::move(second));check(firstState.cancelled==3&&firstState.exited==1&&secondState.entered==1,"tool switch cancel then exit then enter");controller.pointerDown({});controller.documentChanged();check(secondState.cancelled==1,"document switch cancels");
    auto project=fixture();Camera2D camera;camera.center={50,0};camera.pixelsPerMm=5;SizeDip viewport{1000,600};SelectionQuery selection;auto hits=selection.hitTest(project,camera,viewport,camera.worldToDip({25,0},viewport),{},8);check(hits.size()==2,"overlapping walls stable candidates");check(hits[0].id==EntityId("wall-a")&&selection.cycle(hits,1)->id==EntityId("wall-b")&&selection.cycle(hits,2)->id==EntityId("wall-a"),"stable selection cycling");auto lockedHits=selection.hitTest(project,camera,viewport,camera.worldToDip({50,50},viewport),{},8);check(!lockedHits.empty()&&lockedHits[0].locked&&!selection.movable(project,lockedHits[0].id),"locked inspectable not movable");auto hiddenHits=selection.hitTest(project,camera,viewport,camera.worldToDip({25,10},viewport),{},8);for(const auto& hit:hiddenHits)check(hit.id!=EntityId("wall-hidden"),"hidden filtered");
    auto left=camera.worldToDip({25,-20},viewport),right=camera.worldToDip({75,20},viewport);auto enclosed=selection.marquee(project,camera,viewport,left,right);check(!enclosed.contains(EntityId("wall-a")),"left-right requires enclosure");auto crossing=selection.marquee(project,camera,viewport,right,left);check(crossing.contains(EntityId("wall-a"))&&crossing.contains(EntityId("wall-b"))&&crossing.contains(EntityId("wall-locked"))&&!crossing.contains(EntityId("wall-hidden")),"right-left crossing and filters");
    SnapResolver snaps;SnapOptions options;for(double scale:{.1,1.0,10.0}){camera.pixelsPerMm=scale;auto endpointDip=camera.worldToDip({0,0},viewport);endpointDip.y+=6;auto snap=snaps.resolve(project,camera,viewport,endpointDip,options);check(snap&&snap->world.x==0&&snap->world.y==0,"snap radius stable across zoom");snaps.clear();}
    camera.pixelsPerMm=1;auto nearA=camera.worldToDip({0,0},viewport);auto held=snaps.resolve(project,camera,viewport,nearA,options);check(held.has_value(),"snap acquired");auto jitter=nearA;jitter.x+=10;auto stable=snaps.resolve(project,camera,viewport,jitter,options);check(stable&&stable->stableKey==held->stableKey,"12 DIP hysteresis holds");auto cycled=snaps.cycle();check(cycled&&cycled->stableKey!=stable->stableKey,"Tab cycles candidates");
    options.enabled=false;check(!snaps.resolve(project,camera,viewport,nearA,options),"disabled snap releases latch");options.enabled=true;options.supplemental={SnapCandidate{SnapKind::center,{0,0},0,"circle:center","Center",false},SnapCandidate{SnapKind::endpoint,{0,0},0,"underlay:end", "Reference endpoint",true}};auto supplemental=snaps.candidates(project,camera,viewport,nearA,options);check(std::any_of(supplemental.begin(),supplemental.end(),[](const SnapCandidate& candidate){return candidate.kind==SnapKind::center;}),"center source accepted");check(std::none_of(supplemental.begin(),supplemental.end(),[](const SnapCandidate& candidate){return candidate.referenceOnly;}),"reference snap opt in");options.allowReference=true;supplemental=snaps.candidates(project,camera,viewport,nearA,options);check(std::any_of(supplemental.begin(),supplemental.end(),[](const SnapCandidate& candidate){return candidate.referenceOnly;}),"reference snap visibly marked");
    auto flatMarquee=selection.marquee(project,camera,viewport,{400,300},{600,300});check(flatMarquee.contains(EntityId("wall-a")),"zero-height crossing marquee is safe");
    snaps.clear();SnapOptions ortho;ortho.ortho=true;ortho.origin=Point2(0,0);camera.pixelsPerMm=10;auto offAxis=camera.worldToDip({100,1},viewport);auto constrained=snaps.candidates(project,camera,viewport,offAxis,ortho);for(const auto& candidate:constrained)check(std::abs(candidate.world.y)<=epsilon(100),"ortho rejects off-axis snap");
    check(std::abs(*parseNumeric("5' 7 1/2\"",NumericField::length).canonicalValue-1714.5)<1e-9,"numeric length");check(std::abs(*parseNumeric("90 deg",NumericField::angle).canonicalValue-std::numbers::pi/2)<1e-12,"numeric angle");check(!parseNumeric("system('bad')",NumericField::length).canonicalValue,"no expression execution");check(routeSingleLetterShortcut({static_cast<int>('W'),false,false,false,false}),"letter shortcut routed");check(!routeSingleLetterShortcut({static_cast<int>('W'),false,false,false,true}),"focused numeric input suppresses shortcut");
    std::cout<<"input-v1: "<<checks<<" checks PASS; marquee direction, lock/hide, zoom-stable snaps, hysteresis, cancellation\n";return 0;
}catch(const std::exception& error){std::cerr<<"FAIL: "<<error.what()<<'\n';return 1;}}
