#include "editor/plan_viewport.h"
#include "editor/session.h"
#include "render/camera.h"
#include "render/frame_recorder.h"
#include "render/scene.h"
#include <QFile>
#include <QImage>
#include <QtTest>
using namespace kalara;using namespace architecture;using namespace geometry;using namespace render;using namespace editor;
namespace {
EntityHeader h(const char* id,EntityType type,const char* owner,std::optional<EntityId> layer={}){return {EntityId(id),type,EntityId(owner),std::move(layer),0,0};}
Project fixture(std::string projectId="render-project"){Project p{EntityId(projectId)};p.title="Render";EntityId floor("floor"),layer("layer");p.entities.emplace(EntityId("building"),Building{h("building",EntityType::building,projectId.c_str()),"Building",{floor}});p.entities.emplace(floor,Floor{h("floor",EntityType::floor,"building"),"Ground",0,std::nullopt,{EntityId("a"),EntityId("b"),EntityId("c"),EntityId("d"),EntityId("wall-visible"),EntityId("wall-culled")}});p.entities.emplace(layer,Layer{h("layer",EntityType::layer,projectId.c_str()),"Walls"});p.entities.emplace(EntityId("a"),Junction{h("a",EntityType::junction,"floor",layer),floor,{0,0}});p.entities.emplace(EntityId("b"),Junction{h("b",EntityType::junction,"floor",layer),floor,{6000,0}});p.entities.emplace(EntityId("c"),Junction{h("c",EntityType::junction,"floor",layer),floor,{9000000,9000000}});p.entities.emplace(EntityId("d"),Junction{h("d",EntityType::junction,"floor",layer),floor,{9006000,9000000}});p.entities.emplace(EntityId("wall-visible"),Wall{h("wall-visible",EntityType::wall,"floor",layer),floor,EntityId("a"),EntityId("b"),Length(200),ReferenceLine::center,SideConvention::tangentLeftRight,"generic"});p.entities.emplace(EntityId("wall-culled"),Wall{h("wall-culled",EntityType::wall,"floor",layer),floor,EntityId("c"),EntityId("d"),Length(200),ReferenceLine::center,SideConvention::tangentLeftRight,"generic"});return p;}
Project joinFixture(const std::vector<Point2>& endpoints){Project p(EntityId("join-project"));p.title="Joins";EntityId floor("floor"),layer("layer"),center("center");p.entities.emplace(EntityId("building"),Building{h("building",EntityType::building,"join-project"),"Building",{floor}});std::vector<EntityId> members{center};p.entities.emplace(layer,Layer{h("layer",EntityType::layer,"join-project"),"Walls"});p.entities.emplace(center,Junction{h("center",EntityType::junction,"floor",layer),floor,{0,0}});for(std::size_t i=0;i<endpoints.size();++i){auto node=EntityId("node-"+std::to_string(i)),wall=EntityId("wall-"+std::to_string(i));p.entities.emplace(node,Junction{h(node.str().c_str(),EntityType::junction,"floor",layer),floor,endpoints[i]});p.entities.emplace(wall,Wall{h(wall.str().c_str(),EntityType::wall,"floor",layer),floor,center,node,Length(200),ReferenceLine::center,SideConvention::tangentLeftRight,"generic"});members.push_back(node);members.push_back(wall);}p.entities.emplace(floor,Floor{h("floor",EntityType::floor,"building"),"Ground",0,std::nullopt,std::move(members)});return p;}
bool insideFills(Point2 point,const Scene2D& scene){for(const auto& fill:scene.fills)if(locate(point,fill.polygon)!=Location::outside)return true;return false;}
}
class RenderTests:public QObject{
    Q_OBJECT
private slots:
void cameraRoundTripAndAnchor(){Camera2D camera;camera.center={9000000,9000000};camera.pixelsPerMm=.2;const SizeDip viewport{1200,800};for(int i=0;i<1000;++i){Point2 p(8995000+i*9.5,8997000+i*4.5);QVERIFY(near(camera.dipToWorld(camera.worldToDip(p,viewport),viewport),p,10000));}Point2 cursor{213.25,599.75};auto before=camera.dipToWorld(cursor,viewport);camera.zoomAt(cursor,1.2,viewport);auto after=camera.dipToWorld(cursor,viewport);QVERIFY(near(before,after,10000));const auto beforePan=camera.center;camera.panDip({20,-10});QCOMPARE(camera.center.x,beforePan.x-20/camera.pixelsPerMm);QCOMPARE(camera.center.y,beforePan.y-10/camera.pixelsPerMm);}
void sceneCullingAndBounds(){auto project=fixture();SceneIndex index;index.rebuild(project);auto ids=index.query({{-1000,-1000},{7000,1000}},EntityId("floor"));QCOMPARE(ids.size(),std::size_t(1));QCOMPARE(ids[0],EntityId("wall-visible"));SceneBuilder builder;auto scene=builder.build(project,{{{-1000,-1000},{7000,1000}},EntityId("floor")});QCOMPARE(scene.fills.size(),std::size_t(1));QCOMPARE(scene.lines.size(),std::size_t(4));QVERIFY(scene.bounds&&scene.bounds->min.y==-100&&scene.bounds->max.y==100);QCOMPARE(scene.lines[0].sourceRevision,project.revision);}
void derivedWallJoinBoundaries(){SceneBuilder builder;for(const auto& endpoints:std::vector<std::vector<Point2>>{{{2000,0},{0,2000}},{{2000,0},{-1400,-1400}},{{-2000,0},{2000,0},{0,2000}},{{-2000,0},{2000,0},{0,-2000},{0,2000}},{{2000,0},{1999,1}}}){const auto project=joinFixture(endpoints);const auto scene=builder.build(project,{{{-5000,-5000},{5000,5000}},EntityId("floor")});QCOMPARE(scene.fills.size(),endpoints.size());QVERIFY(!scene.lines.empty());for(const auto& line:scene.lines){const auto vector=line.b-line.a;const auto length=norm(vector);QVERIFY(length>epsilon(length));const Vector2 normal{-vector.y/length,vector.x/length};const auto middle=line.a+vector*.5;QVERIFY(insideFills(middle+normal*.001,scene)!=insideFills(middle+normal*-.001,scene));}QVERIFY(scene.bounds&&scene.bounds->min.x>=-2800&&scene.bounds->max.x<=2800&&scene.bounds->min.y>=-2800&&scene.bounds->max.y<=2800);}}
void frameStatistics(){FrameRecorder recorder(5);for(double value:{1,2,3,4,100})recorder.record(value);auto stats=recorder.statistics();QCOMPARE(stats.count,std::size_t(5));QCOMPARE(stats.medianMs,3.0);QCOMPARE(stats.p95Ms,100.0);QCOMPARE(stats.p99Ms,100.0);QCOMPARE(stats.maxMs,100.0);recorder.record(5);QCOMPARE(recorder.samples().size(),std::size_t(5));QVERIFY_THROWS_EXCEPTION(std::invalid_argument,recorder.record(-1));}
void painterParityAndDpi(){auto project=fixture();SceneBuilder builder;auto scene=builder.build(project,{{{-1000,-1000},{7000,1000}},EntityId("floor")});scene.texts.push_back({{3000,300},"6000 mm",150,{32,40,51,255}});PlanViewport painter(nullptr,RendererMode::painter),gpu(nullptr,RendererMode::gpu);painter.resize(800,500);gpu.resize(800,500);painter.setScene(scene);gpu.setScene(scene);painter.camera().fit(*scene.bounds,{800,500});gpu.camera()=painter.camera();for(qreal dpr:{1.0,1.5,2.0}){auto raster=painter.renderImage({800,500},dpr),glShared=gpu.renderImage({800,500},dpr);QCOMPARE(raster,glShared);QCOMPARE(raster.devicePixelRatio(),dpr);QCOMPARE(raster.size(),QSize(qRound(800*dpr),qRound(500*dpr)));const auto file=QStringLiteral(KALARA_SOURCE_DIR "/docs/evidence/step05-painter-%1.png").arg(dpr);QVERIFY(raster.save(file));QVERIFY(raster.pixelColor(raster.width()/2,raster.height()/2)!=raster.pixelColor(0,0));}}
void idleDoesNotRedraw(){PlanViewport painter(nullptr,RendererMode::painter);painter.resize(400,300);painter.show();QVERIFY(QTest::qWaitForWindowExposed(&painter));QTest::qWait(100);const auto frames=painter.frames().samples().size();QVERIFY(frames>0);QTest::qWait(250);QCOMPARE(painter.frames().samples().size(),frames);}
void selectionInteraction(){DocumentSession session("Interaction");auto source=fixture(session.projectStore().snapshot()->id.str());std::vector<runtime::EntityMutation> mutations;for(const auto& [id,entity]:source.entities)mutations.push_back({id,entity});auto snapshot=session.projectStore().snapshot();auto plan=std::get<runtime::ChangePlan>(session.commands().prepare({"fixture.insert",snapshot->id,snapshot->revision,"Insert fixture",mutations}));QVERIFY(std::holds_alternative<runtime::CommitSuccess>(session.commands().commit(plan)));PlanViewport viewport(nullptr,RendererMode::painter);viewport.resize(800,500);viewport.setSession(&session);SceneBuilder builder;auto scene=builder.build(*session.projectStore().snapshot(),{{{-1000,-1000},{7000,1000}},EntityId("floor")});viewport.setScene(scene);viewport.camera().fit(*scene.bounds,{800,500});viewport.show();QVERIFY(QTest::qWaitForWindowExposed(&viewport));auto* canvas=viewport.childAt(400,250);QVERIFY(canvas);const auto hit=viewport.camera().worldToDip({3000,0},{800,500});QTest::mouseClick(canvas,Qt::LeftButton,Qt::NoModifier,QPoint(qRound(hit.x),qRound(hit.y)));QCOMPARE(session.selection().size(),std::size_t(1));QCOMPARE(*session.selection().begin(),EntityId("wall-visible"));const auto before=session.projectStore().snapshot();QTest::mousePress(canvas,Qt::LeftButton,Qt::NoModifier,QPoint(100,100));QVERIFY(viewport.interactionActive());canvas->clearFocus();QCoreApplication::processEvents();QVERIFY(!viewport.interactionActive());QVERIFY(session.projectStore().snapshot()==before);}
void nativeInteractionVisual(){if(QGuiApplication::platformName()!="windows")QSKIP("Native selection visual requires Windows platform");DocumentSession session("Interaction");auto source=fixture(session.projectStore().snapshot()->id.str());std::vector<runtime::EntityMutation> mutations;for(const auto& [id,entity]:source.entities)mutations.push_back({id,entity});auto snapshot=session.projectStore().snapshot();auto plan=std::get<runtime::ChangePlan>(session.commands().prepare({"fixture.insert",snapshot->id,snapshot->revision,"Insert fixture",mutations}));QVERIFY(std::holds_alternative<runtime::CommitSuccess>(session.commands().commit(plan)));PlanViewport viewport(nullptr,RendererMode::painter);viewport.resize(1000,650);viewport.setSession(&session);SceneBuilder builder;auto scene=builder.build(*session.projectStore().snapshot(),{{{-1000,-1000},{7000,1000}},EntityId("floor")});viewport.setScene(scene);viewport.camera().fit(*scene.bounds,{1000,650});viewport.show();QVERIFY(QTest::qWaitForWindowExposed(&viewport));auto* canvas=viewport.childAt(500,325);QVERIFY(canvas);const auto hit=viewport.camera().worldToDip({3000,0},{1000,650});QTest::mouseClick(canvas,Qt::LeftButton,Qt::NoModifier,QPoint(qRound(hit.x),qRound(hit.y)));QCOMPARE(session.selection().size(),std::size_t(1));QVERIFY(viewport.grab().save(QStringLiteral(KALARA_SOURCE_DIR "/docs/evidence/step06-selected.png")));QTest::mousePress(canvas,Qt::LeftButton,Qt::NoModifier,QPoint(850,150));QTest::mouseMove(canvas,QPoint(150,500),50);QVERIFY(viewport.interactionActive());QVERIFY(viewport.grab().save(QStringLiteral(KALARA_SOURCE_DIR "/docs/evidence/step06-crossing-marquee.png")));QTest::mouseRelease(canvas,Qt::LeftButton,Qt::NoModifier,QPoint(150,500));QVERIFY(!viewport.interactionActive());}
void wallToolInteraction(){DocumentSession session("Wall UI");PlanViewport viewport(nullptr,RendererMode::painter);viewport.resize(1000,650);viewport.setSession(&session);viewport.activateWallTool();viewport.show();QVERIFY(QTest::qWaitForWindowExposed(&viewport));auto* canvas=viewport.childAt(500,325);QVERIFY(canvas);QTest::mouseClick(canvas,Qt::LeftButton,Qt::NoModifier,QPoint(300,325));QCOMPARE(session.commands().undoCount(),std::size_t(0));QTest::mouseMove(canvas,QPoint(700,325),20);QCOMPARE(viewport.commitWallNumeric(QGuiApplication::platformName()=="windows"?"@6000,0":"6000"),std::string());QCOMPARE(session.commands().undoCount(),std::size_t(1));std::size_t wallCount=0;const Wall* wall=nullptr;for(const auto& [id,entity]:session.projectStore().snapshot()->entities)if(const auto* found=std::get_if<Wall>(&entity)){wall=found;++wallCount;}QCOMPARE(wallCount,std::size_t(1));QVERIFY(wall);const auto wallId=wall->header.id;const auto snapshot=session.projectStore().snapshot();const auto a=std::get<Junction>(*snapshot->find(wall->startJunctionId)).position,b=std::get<Junction>(*snapshot->find(wall->endJunctionId)).position;QCOMPARE(distance(a,b).mm,6000.0);const auto shared=wall->endJunctionId;QVERIFY(!viewport.commitWallNumeric("bad input").empty());QTest::mouseMove(canvas,QPoint(700,200),20);QCOMPARE(viewport.commitWallNumeric("@1000,2000"),std::string());QCOMPARE(session.commands().undoCount(),std::size_t(2));std::size_t incidence=0;for(const auto& [id,entity]:session.projectStore().snapshot()->entities)if(const auto* found=std::get_if<Wall>(&entity))if(found->startJunctionId==shared||found->endJunctionId==shared)++incidence;QCOMPARE(incidence,std::size_t(2));QTest::keyClick(canvas,Qt::Key_Escape);QCOMPARE(session.commands().undoCount(),std::size_t(2));QTest::mouseDClick(canvas,Qt::LeftButton,Qt::NoModifier,QPoint(700,325));QCOMPARE(session.commands().undoCount(),std::size_t(2));viewport.activateSelectTool();session.select({wallId});const auto beforeMove=session.projectStore().snapshot();QTest::mousePress(canvas,Qt::LeftButton,Qt::NoModifier,QPoint(600,325));QTest::mouseMove(canvas,QPoint(620,345),20);QVERIFY(viewport.interactionActive());QCOMPARE(session.projectStore().snapshot(),beforeMove);QTest::keyClick(canvas,Qt::Key_Escape);QCOMPARE(session.projectStore().snapshot(),beforeMove);QTest::mousePress(canvas,Qt::LeftButton,Qt::NoModifier,QPoint(600,325));QTest::mouseMove(canvas,QPoint(620,345),20);QTest::mouseRelease(canvas,Qt::LeftButton,Qt::NoModifier,QPoint(620,345));QCOMPARE(session.commands().undoCount(),std::size_t(3));if(QGuiApplication::platformName()=="windows")QVERIFY(viewport.grab().save(QStringLiteral(KALARA_SOURCE_DIR "/docs/evidence/step07-wall-tool.png")));}
void sharedJunctionMovePreview(){DocumentSession session("Junction UI");QVERIFY(std::holds_alternative<runtime::CommitSuccess>(session.walls().addRectangle(session.activeFloorId(),session.wallLayerId(),{0,0},{6000,4000})));const auto snapshot=session.projectStore().snapshot();const Junction* node=nullptr;for(const auto& [id,entity]:snapshot->entities)if(const auto* found=std::get_if<Junction>(&entity);found&&found->position.x==0&&found->position.y==0){node=found;break;}QVERIFY(node);PlanViewport viewport(nullptr,RendererMode::painter);viewport.resize(1000,650);viewport.setSession(&session);SceneBuilder builder;auto scene=builder.build(*snapshot,{{{-1000,-1000},{7000,5000}},session.activeFloorId()});viewport.setScene(scene);viewport.camera().fit(*scene.bounds,{1000,650});viewport.show();QVERIFY(QTest::qWaitForWindowExposed(&viewport));auto* canvas=viewport.childAt(500,325);QVERIFY(canvas);session.select({node->header.id});const auto point=viewport.camera().worldToDip(node->position,{1000,650});QTest::mousePress(canvas,Qt::LeftButton,Qt::NoModifier,QPoint(qRound(point.x),qRound(point.y)));QTest::mouseMove(canvas,QPoint(qRound(point.x+20),qRound(point.y-20)),20);QVERIFY(viewport.interactionActive());QCOMPARE(session.projectStore().snapshot(),snapshot);QTest::keyClick(canvas,Qt::Key_Escape);QCOMPARE(session.projectStore().snapshot(),snapshot);}
};
QTEST_MAIN(RenderTests)
#include "render_tests.moc"
