#include "editor/plan_viewport.h"
#include "render/camera.h"
#include "render/frame_recorder.h"
#include "render/scene.h"
#include <QFile>
#include <QImage>
#include <QtTest>
using namespace kalara;using namespace architecture;using namespace geometry;using namespace render;using namespace editor;
namespace {
EntityHeader h(const char* id,EntityType type,const char* owner,std::optional<EntityId> layer={}){return {EntityId(id),type,EntityId(owner),std::move(layer),0,0};}
Project fixture(){Project p(EntityId("render-project"));p.title="Render";EntityId floor("floor"),layer("layer");p.entities.emplace(EntityId("building"),Building{h("building",EntityType::building,"render-project"),"Building",{floor}});p.entities.emplace(floor,Floor{h("floor",EntityType::floor,"building"),"Ground",0,std::nullopt,{EntityId("a"),EntityId("b"),EntityId("c"),EntityId("d"),EntityId("wall-visible"),EntityId("wall-culled")}});p.entities.emplace(layer,Layer{h("layer",EntityType::layer,"render-project"),"Walls"});p.entities.emplace(EntityId("a"),Junction{h("a",EntityType::junction,"floor",layer),floor,{0,0}});p.entities.emplace(EntityId("b"),Junction{h("b",EntityType::junction,"floor",layer),floor,{6000,0}});p.entities.emplace(EntityId("c"),Junction{h("c",EntityType::junction,"floor",layer),floor,{9000000,9000000}});p.entities.emplace(EntityId("d"),Junction{h("d",EntityType::junction,"floor",layer),floor,{9006000,9000000}});p.entities.emplace(EntityId("wall-visible"),Wall{h("wall-visible",EntityType::wall,"floor",layer),floor,EntityId("a"),EntityId("b"),Length(200),ReferenceLine::center,SideConvention::tangentLeftRight,"generic"});p.entities.emplace(EntityId("wall-culled"),Wall{h("wall-culled",EntityType::wall,"floor",layer),floor,EntityId("c"),EntityId("d"),Length(200),ReferenceLine::center,SideConvention::tangentLeftRight,"generic"});return p;}
}
class RenderTests:public QObject{
    Q_OBJECT
private slots:
void cameraRoundTripAndAnchor(){Camera2D camera;camera.center={9000000,9000000};camera.pixelsPerMm=.2;const SizeDip viewport{1200,800};for(int i=0;i<1000;++i){Point2 p(8995000+i*9.5,8997000+i*4.5);QVERIFY(near(camera.dipToWorld(camera.worldToDip(p,viewport),viewport),p,10000));}Point2 cursor{213.25,599.75};auto before=camera.dipToWorld(cursor,viewport);camera.zoomAt(cursor,1.2,viewport);auto after=camera.dipToWorld(cursor,viewport);QVERIFY(near(before,after,10000));const auto beforePan=camera.center;camera.panDip({20,-10});QCOMPARE(camera.center.x,beforePan.x-20/camera.pixelsPerMm);QCOMPARE(camera.center.y,beforePan.y-10/camera.pixelsPerMm);}
void sceneCullingAndBounds(){auto project=fixture();SceneIndex index;index.rebuild(project);auto ids=index.query({{-1000,-1000},{7000,1000}},EntityId("floor"));QCOMPARE(ids.size(),std::size_t(1));QCOMPARE(ids[0],EntityId("wall-visible"));SceneBuilder builder;auto scene=builder.build(project,{{{-1000,-1000},{7000,1000}},EntityId("floor")});QCOMPARE(scene.fills.size(),std::size_t(1));QCOMPARE(scene.lines.size(),std::size_t(2));QVERIFY(scene.bounds&&scene.bounds->min.y==-100&&scene.bounds->max.y==100);QCOMPARE(scene.lines[0].sourceRevision,project.revision);}
void frameStatistics(){FrameRecorder recorder(5);for(double value:{1,2,3,4,100})recorder.record(value);auto stats=recorder.statistics();QCOMPARE(stats.count,std::size_t(5));QCOMPARE(stats.medianMs,3.0);QCOMPARE(stats.p95Ms,100.0);QCOMPARE(stats.p99Ms,100.0);QCOMPARE(stats.maxMs,100.0);recorder.record(5);QCOMPARE(recorder.samples().size(),std::size_t(5));QVERIFY_THROWS_EXCEPTION(std::invalid_argument,recorder.record(-1));}
void painterParityAndDpi(){auto project=fixture();SceneBuilder builder;auto scene=builder.build(project,{{{-1000,-1000},{7000,1000}},EntityId("floor")});scene.texts.push_back({{3000,300},"6000 mm",150,{32,40,51,255}});PlanViewport painter(nullptr,RendererMode::painter),gpu(nullptr,RendererMode::gpu);painter.resize(800,500);gpu.resize(800,500);painter.setScene(scene);gpu.setScene(scene);painter.camera().fit(*scene.bounds,{800,500});gpu.camera()=painter.camera();for(qreal dpr:{1.0,1.5,2.0}){auto raster=painter.renderImage({800,500},dpr),glShared=gpu.renderImage({800,500},dpr);QCOMPARE(raster,glShared);QCOMPARE(raster.devicePixelRatio(),dpr);QCOMPARE(raster.size(),QSize(qRound(800*dpr),qRound(500*dpr)));const auto file=QStringLiteral(KALARA_SOURCE_DIR "/docs/evidence/step05-painter-%1.png").arg(dpr);QVERIFY(raster.save(file));QVERIFY(raster.pixelColor(raster.width()/2,raster.height()/2)!=raster.pixelColor(0,0));}}
void idleDoesNotRedraw(){PlanViewport painter(nullptr,RendererMode::painter);painter.resize(400,300);painter.show();QVERIFY(QTest::qWaitForWindowExposed(&painter));QTest::qWait(100);const auto frames=painter.frames().samples().size();QVERIFY(frames>0);QTest::qWait(250);QCOMPARE(painter.frames().samples().size(),frames);}
};
QTEST_MAIN(RenderTests)
#include "render_tests.moc"
