#include "architecture/wall_authoring.h"
#include <iostream>
#include <stdexcept>
using namespace kalara;using namespace architecture;using namespace geometry;using namespace runtime;
namespace {
int checks=0;void check(bool value,const char* message){++checks;if(!value)throw std::runtime_error(message);}
Project fixture(){Project p(EntityId("wall-project"));p.title="Walls";EntityHeader building{EntityId("building"),EntityType::building,p.id,std::nullopt,0,0},floor{EntityId("floor"),EntityType::floor,building.id,std::nullopt,0,0},layer{EntityId("walls"),EntityType::layer,p.id,std::nullopt,0,0};p.entities.emplace(building.id,Building{building,"Building",{floor.id}});p.entities.emplace(floor.id,Floor{floor,"Ground",0,std::nullopt,{}});p.entities.emplace(layer.id,Layer{layer,"Walls",true,false,true});return p;}
std::vector<const Wall*> walls(const Project& project){std::vector<const Wall*> result;for(const auto& [id,entity]:project.entities)if(auto* wall=std::get_if<Wall>(&entity))result.push_back(wall);return result;}
std::vector<const Junction*> junctions(const Project& project){std::vector<const Junction*> result;for(const auto& [id,entity]:project.entities)if(auto* node=std::get_if<Junction>(&entity))result.push_back(node);return result;}
}
int main(){try{ProjectStore store(fixture());CommandService commands(store);WallAuthoring author(store,commands);const EntityId floor("floor"),layer("walls");
    auto rectangle=author.addRectangle(floor,layer,{0,0},{6000,4000});check(std::holds_alternative<CommitSuccess>(rectangle),"rectangle commits");auto snapshot=store.snapshot();check(walls(*snapshot).size()==4&&junctions(*snapshot).size()==4,"rectangle is four walls and four shared nodes");double axisArea=0;for(const auto* wall:walls(*snapshot)){const auto& a=std::get<Junction>(*snapshot->find(wall->startJunctionId));const auto& b=std::get<Junction>(*snapshot->find(wall->endJunctionId));axisArea+=a.position.x*b.position.y-b.position.x*a.position.y;check(wall->thickness.mm==200,"default exterior thickness");}check(std::abs(axisArea*.5-24000000)<1e-6,"exact 6000 x 4000 centerline enclosure");check(commands.undoCount()==1,"rectangle is one command");check(std::holds_alternative<CommitSuccess>(commands.undo())&&walls(*store.snapshot()).empty(),"undo restores empty topology");check(std::holds_alternative<CommitSuccess>(commands.redo()),"rectangle redo");
    snapshot=store.snapshot();auto existing=*junctions(*snapshot).front();auto segment=author.addSegment(floor,layer,{existing.position,existing.header.id},{{8000,4000},std::nullopt});check(std::holds_alternative<CommitSuccess>(segment),"chain segment commits");auto after=store.snapshot();check(walls(*after).size()==5&&junctions(*after).size()==5,"explicit endpoint reuses stable junction");const auto beforeInvalid=after;auto duplicate=author.addSegment(floor,layer,{existing.position,existing.header.id},{existing.position,existing.header.id});check(std::holds_alternative<CommitFailure>(duplicate)&&store.snapshot()==beforeInvalid,"duplicate endpoint rejected without commit");
    const Wall* added=nullptr;EntityId movedId("pending");for(const auto* candidate:walls(*after)){const auto& end=std::get<Junction>(*after->find(candidate->endJunctionId));if(end.position.x==8000){added=candidate;movedId=candidate->endJunctionId;break;}}check(added!=nullptr,"new segment identified by topology");const auto addedId=added->header.id;check(std::holds_alternative<CommitSuccess>(author.moveJunction(movedId,{8500,4500})),"junction move commits");check(std::get<Junction>(*store.snapshot()->find(movedId)).position.x==8500,"junction move is exact");check(std::holds_alternative<CommitSuccess>(commands.undo())&&std::get<Junction>(*store.snapshot()->find(movedId)).position.x==8000,"undo restores junction topology");check(std::holds_alternative<CommitSuccess>(author.changeThickness(addedId,Length(150),ReferenceLine::left)),"thickness edit commits");auto edited=std::get<Wall>(*store.snapshot()->find(addedId));check(edited.thickness.mm==150&&edited.referenceLine==ReferenceLine::left,"thickness and preserved face policy stored");
    auto tiny=author.addSegment(floor,layer,{{9000,0},{}},{{9000.001,0},{}},WallSpec{Length(.0001),"Tiny",ReferenceLine::center});check(std::holds_alternative<CommitSuccess>(tiny),"tiny valid wall has no planning minimum");std::cout<<"wall-authoring-v1: "<<checks<<" checks PASS; exact rectangle, explicit topology, atomic undo, tiny valid segment\n";return 0;}catch(const std::exception& error){std::cerr<<"FAIL: "<<error.what()<<'\n';return 1;}}
