#include "architecture/wall_authoring.h"
#include <array>
#include <cmath>

namespace kalara::architecture {
namespace {
runtime::CommitFailure fail(std::string code,std::string message){return {{{std::move(code),Severity::error,std::move(message),{},"","Correct the wall input and retry"}}};}
bool validPoint(geometry::Point2 p){return std::isfinite(p.x)&&std::isfinite(p.y)&&std::abs(p.x)<=10000000&&std::abs(p.y)<=10000000;}
EntityHeader makeHeader(EntityId id,EntityType type,EntityId owner,std::optional<EntityId> layer={}){return {std::move(id),type,std::move(owner),std::move(layer),0,0};}
}
runtime::CommitResult WallAuthoring::failure(std::string code,std::string message)const{return fail(std::move(code),std::move(message));}
runtime::CommitResult WallAuthoring::apply(runtime::CommandRequest request){auto prepared=commands_.prepare(request);if(auto* rejected=std::get_if<runtime::PrepareFailure>(&prepared))return runtime::CommitFailure{rejected->diagnostics};return commands_.commit(std::get<runtime::ChangePlan>(std::move(prepared)));}
runtime::CommitResult WallAuthoring::addSegment(const EntityId& floorId,const EntityId& layerId,WallEndpoint start,WallEndpoint end,const WallSpec& spec){
    auto snapshot=store_.snapshot();const auto* floorEntity=snapshot->find(floorId),*layer=snapshot->find(layerId);if(!floorEntity||header(*floorEntity).type!=EntityType::floor)return failure("wall.floor","Active floor is missing");if(!layer||header(*layer).type!=EntityType::layer)return failure("wall.layer","Wall layer is missing");if(std::get<Layer>(*layer).locked)return failure("wall.layer.locked","Wall layer is locked");if(!validPoint(start.position)||!validPoint(end.position))return failure("wall.range","Wall endpoint exceeds the supported coordinate envelope");if(geometry::near(start.position,end.position,geometry::distance(start.position,end.position).mm))return failure("wall.length.zero","Wall endpoints must be distinct");if(!std::isfinite(spec.thickness.mm)||spec.thickness.mm<=geometry::epsilon(spec.thickness.mm))return failure("wall.thickness","Wall thickness must be positive");
    auto resolve=[&](WallEndpoint endpoint)->std::optional<EntityId>{if(!endpoint.junctionId)return{};const auto* value=snapshot->find(*endpoint.junctionId);if(!value||header(*value).type!=EntityType::junction)return{};const auto& junction=std::get<Junction>(*value);if(junction.floorId!=floorId||junction.position.x!=endpoint.position.x||junction.position.y!=endpoint.position.y)return{};return endpoint.junctionId;};
    auto startId=resolve(start),endId=resolve(end);if(start.junctionId&&!startId)return failure("wall.junction.start","Requested start junction does not match the endpoint");if(end.junctionId&&!endId)return failure("wall.junction.end","Requested end junction does not match the endpoint");if(startId&&endId&&*startId==*endId)return failure("wall.length.zero","A wall cannot connect a junction to itself");
    if(!startId)startId=EntityId::generate();if(!endId)endId=EntityId::generate();const auto wallId=EntityId::generate();auto floor=std::get<Floor>(*floorEntity);std::vector<runtime::EntityMutation> mutations;
    if(!snapshot->find(*startId)){Junction junction{makeHeader(*startId,EntityType::junction,floorId,layerId),floorId,start.position};mutations.push_back({*startId,Entity(junction)});floor.entityIds.push_back(*startId);}if(!snapshot->find(*endId)){Junction junction{makeHeader(*endId,EntityType::junction,floorId,layerId),floorId,end.position};mutations.push_back({*endId,Entity(junction)});floor.entityIds.push_back(*endId);}
    Wall wall{makeHeader(wallId,EntityType::wall,floorId,layerId),floorId,*startId,*endId,spec.thickness,spec.referenceLine,SideConvention::tangentLeftRight,spec.wallType};mutations.push_back({wallId,Entity(wall)});floor.entityIds.push_back(wallId);mutations.push_back({floorId,Entity(floor)});
    auto result=apply({"wall.add_segment",snapshot->id,snapshot->revision,"Draw wall segment",std::move(mutations),"Active floor","One connected semantic segment"});if(std::holds_alternative<runtime::CommitSuccess>(result))lastEndJunction_=*endId;return result;
}
runtime::CommitResult WallAuthoring::addRectangle(const EntityId& floorId,const EntityId& layerId,geometry::Point2 first,geometry::Point2 opposite,const WallSpec& spec){
    if(!validPoint(first)||!validPoint(opposite))return failure("wall.range","Rectangle exceeds the supported coordinate envelope");if(std::abs(first.x-opposite.x)<=geometry::epsilon(std::abs(first.x-opposite.x))||std::abs(first.y-opposite.y)<=geometry::epsilon(std::abs(first.y-opposite.y)))return failure("wall.rectangle.zero","Rectangle width and height must be positive");auto snapshot=store_.snapshot();const auto* floorEntity=snapshot->find(floorId),*layer=snapshot->find(layerId);if(!floorEntity||header(*floorEntity).type!=EntityType::floor)return failure("wall.floor","Active floor is missing");if(!layer||header(*layer).type!=EntityType::layer||std::get<Layer>(*layer).locked)return failure("wall.layer","Wall layer is unavailable or locked");
    std::array<geometry::Point2,4> points={first,geometry::Point2{opposite.x,first.y},opposite,geometry::Point2{first.x,opposite.y}};std::array<EntityId,4> nodes={EntityId::generate(),EntityId::generate(),EntityId::generate(),EntityId::generate()};auto floor=std::get<Floor>(*floorEntity);std::vector<runtime::EntityMutation> mutations;
    for(std::size_t i=0;i<4;++i){Junction junction{makeHeader(nodes[i],EntityType::junction,floorId,layerId),floorId,points[i]};mutations.push_back({nodes[i],Entity(junction)});floor.entityIds.push_back(nodes[i]);}
    for(std::size_t i=0;i<4;++i){auto id=EntityId::generate();Wall wall{makeHeader(id,EntityType::wall,floorId,layerId),floorId,nodes[i],nodes[(i+1)%4],spec.thickness,spec.referenceLine,SideConvention::tangentLeftRight,spec.wallType};mutations.push_back({id,Entity(wall)});floor.entityIds.push_back(id);}mutations.push_back({floorId,Entity(floor)});
    return apply({"wall.add_rectangle",snapshot->id,snapshot->revision,"Draw wall rectangle",std::move(mutations),"Active floor","Four connected walls in one command"});
}
runtime::CommitResult WallAuthoring::moveJunction(const EntityId& id,geometry::Point2 position){auto snapshot=store_.snapshot();const auto* value=snapshot->find(id);if(!value||header(*value).type!=EntityType::junction)return failure("wall.junction","Junction does not exist");if(!validPoint(position))return failure("wall.range","Junction exceeds the supported coordinate envelope");auto junction=std::get<Junction>(*value);junction.position=position;return apply({"wall.move_junction",snapshot->id,snapshot->revision,"Move connected junction",{{id,Entity(junction)}},"Connected junction","Incident walls retain the shared junction ID"});}
runtime::CommitResult WallAuthoring::translateWall(const EntityId& id,geometry::Vector2 delta){auto snapshot=store_.snapshot();const auto* value=snapshot->find(id);if(!value||header(*value).type!=EntityType::wall)return failure("wall.missing","Wall does not exist");const auto& wall=std::get<Wall>(*value);const auto* av=snapshot->find(wall.startJunctionId),*bv=snapshot->find(wall.endJunctionId);if(!av||!bv)return failure("wall.topology","Wall junction is missing");auto a=std::get<Junction>(*av),b=std::get<Junction>(*bv);a.position=a.position+delta;b.position=b.position+delta;if(!validPoint(a.position)||!validPoint(b.position))return failure("wall.range","Translation exceeds the supported coordinate envelope");return apply({"wall.translate",snapshot->id,snapshot->revision,"Translate wall",{{a.header.id,Entity(a)},{b.header.id,Entity(b)}},"Wall endpoints","Shared endpoints move with incident walls"});}
runtime::CommitResult WallAuthoring::changeThickness(const EntityId& id,geometry::Length thickness,ReferenceLine preserve,std::string wallType){auto snapshot=store_.snapshot();const auto* value=snapshot->find(id);if(!value||header(*value).type!=EntityType::wall)return failure("wall.missing","Wall does not exist");if(!std::isfinite(thickness.mm)||thickness.mm<=geometry::epsilon(thickness.mm))return failure("wall.thickness","Wall thickness must be positive");auto wall=std::get<Wall>(*value);wall.thickness=thickness;wall.referenceLine=preserve;if(!wallType.empty())wall.wallType=std::move(wallType);return apply({"wall.properties",snapshot->id,snapshot->revision,"Change wall properties",{{id,Entity(wall)}},"Selected wall","Preserve selected reference line"});}
}
