#include "editor/input_system.h"
#include <algorithm>
#include <array>
#include <cctype>
#include <cmath>
#include <numbers>
#include <regex>
#include <stdexcept>
namespace kalara::editor {
using namespace architecture;using namespace geometry;
namespace {
double dipDistance(Point2 a,Point2 b){return std::hypot(a.x-b.x,a.y-b.y);}
bool contains(AABB2 box,Point2 p){return p.x>=box.min.x&&p.x<=box.max.x&&p.y>=box.min.y&&p.y<=box.max.y;}
bool intersects(AABB2 a,AABB2 b){return a.min.x<=b.max.x&&a.max.x>=b.min.x&&a.min.y<=b.max.y&&a.max.y>=b.min.y;}
int snapPriority(SnapKind kind){switch(kind){case SnapKind::junction:return 0;case SnapKind::endpoint:return 1;case SnapKind::intersection:return 2;case SnapKind::midpoint:return 3;case SnapKind::perpendicular:return 4;case SnapKind::center:return 5;case SnapKind::alignment:return 6;case SnapKind::hostProjection:return 7;case SnapKind::nearest:return 8;case SnapKind::grid:return 9;}return 10;}
std::optional<std::pair<Segment2,bool>> wallSegment(const Project& project,const Entity& entity){const auto* wall=std::get_if<Wall>(&entity);if(!wall)return{};const auto* a=project.find(wall->startJunctionId),*b=project.find(wall->endJunctionId);if(!a||!b)return{};bool locked=false;const auto* layer=wall->header.layerId?project.find(*wall->header.layerId):nullptr;if(layer){const auto& value=std::get<Layer>(*layer);if(!value.visible)return{};locked=value.locked;}return std::pair{Segment2(std::get<Junction>(*a).position,std::get<Junction>(*b).position),locked};}
Point2 constrainedPoint(Point2 world,const SnapOptions& options){if(!options.origin||(!options.ortho&&!options.polar))return world;const auto vector=world-*options.origin;const double length=norm(vector);if(length<=epsilon(length))return *options.origin;double angle=std::atan2(vector.y,vector.x);const double increment=options.ortho?std::numbers::pi/2:options.polarIncrementRadians;if(!std::isfinite(increment)||increment<=0)throw std::invalid_argument("Polar increment must be positive");angle=std::round(angle/increment)*increment;return *options.origin+Vector2{std::cos(angle)*length,std::sin(angle)*length};}
}
void ToolController::activate(std::unique_ptr<Tool> tool){if(active_){active_->cancel();active_->exit();}active_=std::move(tool);if(active_)active_->enter();}
void ToolController::pointerDown(const PointerEvent& e){if(active_)active_->pointerDown(e);}void ToolController::pointerMove(const PointerEvent& e){if(active_)active_->pointerMove(e);}void ToolController::pointerUp(const PointerEvent& e){if(active_)active_->pointerUp(e);}void ToolController::key(const KeyEvent& e){if(active_)active_->key(e);}void ToolController::cancel(){if(active_)active_->cancel();}void ToolController::focusLost(){cancel();}void ToolController::documentChanged(){cancel();}void ToolController::floorChanged(){cancel();}
bool SelectionQuery::eligible(const Project& project,const Entity& entity,bool& locked){locked=false;const auto& h=header(entity);if(h.layerId){const auto* found=project.find(*h.layerId);if(!found||header(*found).type!=EntityType::layer)return false;const auto& layer=std::get<Layer>(*found);if(!layer.visible)return false;locked=layer.locked;}return true;}
std::vector<Hit> SelectionQuery::hitTest(const Project& project,const render::Camera2D& camera,render::SizeDip viewport,Point2 cursor,const std::set<EntityId>& selected,double radius)const{
    std::vector<Hit> hits;for(const auto& [id,entity]:project.entities){bool locked;if(!eligible(project,entity,locked))continue;if(const auto* opening=std::get_if<Opening>(&entity)){const auto* host=project.find(opening->hostWallId);auto wall=host?wallSegment(project,*host):std::nullopt;if(wall){const auto axis=wall->first.b-wall->first.a;const double length=norm(axis);if(length>epsilon(length)){const auto unit=axis*(1/length);const auto center=wall->first.a+unit*opening->centerOffset.mm;const auto distance=dipDistance(cursor,camera.worldToDip(center,viewport));if(distance<=radius*1.5)hits.push_back({id,selected.contains(id)?HitPriority::selectedControl:HitPriority::grip,distance,locked});}}}else if(auto wall=wallSegment(project,entity)){const auto a=camera.worldToDip(wall->first.a,viewport),b=camera.worldToDip(wall->first.b,viewport);const double length=dipDistance(a,b);const double distance=length<=epsilon(length)?dipDistance(cursor,a):dipDistance(cursor,nearestPoint(cursor,{a,b}));if(distance<=radius)hits.push_back({id,selected.contains(id)?HitPriority::selectedControl:HitPriority::wall,distance,locked});}else if(const auto* junction=std::get_if<Junction>(&entity)){const double distance=dipDistance(cursor,camera.worldToDip(junction->position,viewport));if(distance<=radius)hits.push_back({id,selected.contains(id)?HitPriority::grip:HitPriority::selectedControl,distance,locked});}}
    std::sort(hits.begin(),hits.end(),[](const Hit& a,const Hit& b){if(a.priority!=b.priority)return a.priority<b.priority;if(a.distanceDip!=b.distanceDip)return a.distanceDip<b.distanceDip;return a.id<b.id;});return hits;
}
std::set<EntityId> SelectionQuery::marquee(const Project& project,const render::Camera2D& camera,render::SizeDip viewport,Point2 start,Point2 end)const{
    const bool enclosed=start.x<=end.x;AABB2 box{{std::min(start.x,end.x),std::min(start.y,end.y)},{std::max(start.x,end.x),std::max(start.y,end.y)}};if(box.max.x-box.min.x<1e-6){box.min.x-=.5;box.max.x+=.5;}if(box.max.y-box.min.y<1e-6){box.min.y-=.5;box.max.y+=.5;}std::set<EntityId> result;
    for(const auto& [id,entity]:project.entities){bool locked;if(!eligible(project,entity,locked))continue;if(auto wall=wallSegment(project,entity)){const auto a=camera.worldToDip(wall->first.a,viewport),b=camera.worldToDip(wall->first.b,viewport);bool selected=enclosed?(contains(box,a)&&contains(box,b)):(contains(box,a)||contains(box,b));if(!enclosed&&!selected){const std::array<Segment2,4> edges={Segment2(box.min,{box.max.x,box.min.y}),Segment2({box.max.x,box.min.y},box.max),Segment2(box.max,{box.min.x,box.max.y}),Segment2({box.min.x,box.max.y},box.min)};for(const auto& edge:edges)if(!intersections({a,b},edge).empty()){selected=true;break;}}if(selected)result.insert(id);}else if(const auto* junction=std::get_if<Junction>(&entity)){if(contains(box,camera.worldToDip(junction->position,viewport)))result.insert(id);}}
    return result;
}
bool SelectionQuery::movable(const Project& project,const EntityId& id)const{const auto* entity=project.find(id);if(!entity)return false;bool locked;return eligible(project,*entity,locked)&&!locked;}
std::optional<Hit> SelectionQuery::cycle(const std::vector<Hit>& hits,std::size_t index)const{if(hits.empty())return{};return hits[index%hits.size()];}
Point2 SnapResolver::constrain(Point2 world,const SnapOptions& options){return constrainedPoint(world,options);}
std::vector<SnapCandidate> SnapResolver::candidates(const Project& project,const render::Camera2D& camera,render::SizeDip viewport,Point2 cursorDip,const SnapOptions& options)const{
    if(!options.enabled)return{};const auto rawWorld=camera.dipToWorld(cursorDip,viewport),target=constrain(rawWorld,options);const auto targetDip=camera.worldToDip(target,viewport);std::vector<SnapCandidate> result;std::vector<std::pair<EntityId,Segment2>> walls;
    auto add=[&](SnapKind kind,Point2 world,std::string key,std::string label,bool referenceOnly=false){const auto dip=camera.worldToDip(world,viewport);const double distance=dipDistance(dip,targetDip);if(distance<=options.radiusDip&&(!referenceOnly||options.allowReference))result.push_back({kind,world,distance,std::move(key),std::move(label),referenceOnly});};
    for(const auto& [id,entity]:project.entities){bool locked;if(!SelectionQuery::eligible(project,entity,locked))continue;if(const auto* junction=std::get_if<Junction>(&entity)){add(SnapKind::junction,junction->position,"junction:"+id.str(),"Junction");add(SnapKind::alignment,{junction->position.x,target.y},"alignment-x:"+id.str(),"Align X");add(SnapKind::alignment,{target.x,junction->position.y},"alignment-y:"+id.str(),"Align Y");}if(auto wall=wallSegment(project,entity)){walls.push_back({id,wall->first});add(SnapKind::endpoint,wall->first.a,"endpoint:"+id.str()+":start","Endpoint");add(SnapKind::endpoint,wall->first.b,"endpoint:"+id.str()+":end","Endpoint");add(SnapKind::midpoint,wall->first.a+(wall->first.b-wall->first.a)*.5,"midpoint:"+id.str(),"Midpoint");const auto nearest=nearestPoint(target,wall->first);add(options.origin?SnapKind::perpendicular:SnapKind::nearest,nearest,"nearest:"+id.str(),options.origin?"Perpendicular":"Nearest");add(SnapKind::hostProjection,nearest,"host:"+id.str(),"Host projection");}}
    for(std::size_t i=0;i<walls.size();++i)for(std::size_t j=i+1;j<walls.size();++j)for(auto p:intersections(walls[i].second,walls[j].second))add(SnapKind::intersection,p,"intersection:"+walls[i].first.str()+":"+walls[j].first.str(),"Intersection");
    if(options.grid&&options.gridMm>0&&std::isfinite(options.gridMm)){Point2 grid(std::round(target.x/options.gridMm)*options.gridMm,std::round(target.y/options.gridMm)*options.gridMm);add(SnapKind::grid,grid,"grid:"+std::to_string(grid.x)+":"+std::to_string(grid.y),"Grid");}
    for(const auto& candidate:options.supplemental)add(candidate.kind,candidate.world,candidate.stableKey,candidate.label,candidate.referenceOnly);
    if(options.origin&&(options.ortho||options.polar)){std::erase_if(result,[&](const SnapCandidate& candidate){const auto constrainedCandidate=constrain(candidate.world,options);return dipDistance(camera.worldToDip(constrainedCandidate,viewport),camera.worldToDip(candidate.world,viewport))>epsilon(options.radiusDip);});}
    std::sort(result.begin(),result.end(),[](const SnapCandidate& a,const SnapCandidate& b){const int ap=snapPriority(a.kind),bp=snapPriority(b.kind);if(ap!=bp)return ap<bp;if(a.distanceDip!=b.distanceDip)return a.distanceDip<b.distanceDip;return a.stableKey<b.stableKey;});return result;
}
std::optional<SnapCandidate> SnapResolver::resolve(const Project& project,const render::Camera2D& camera,render::SizeDip viewport,Point2 cursor,const SnapOptions& options){
    if(!options.enabled){clear();return{};}
    if(latched_){const double distance=dipDistance(camera.worldToDip(latched_->world,viewport),cursor);if(distance<=options.hysteresisDip){latched_->distanceDip=distance;return latched_;}}
    ranked_=candidates(project,camera,viewport,cursor,options);cycleIndex_=0;latched_=ranked_.empty()?std::nullopt:std::optional<SnapCandidate>(ranked_[0]);return latched_;
}
std::optional<SnapCandidate> SnapResolver::cycle(){if(ranked_.empty())return{};cycleIndex_=(cycleIndex_+1)%ranked_.size();latched_=ranked_[cycleIndex_];return latched_;}
NumericResult parseNumeric(std::string_view text,NumericField field,Unit displayUnit){
    if(field!=NumericField::angle){auto parsed=parseLength(text,displayUnit);return {parsed.value?std::optional<double>(parsed.value->mm):std::nullopt,parsed.error};}
    try{std::string value(text);static const std::regex pattern(R"(^\s*([+-]?(?:\d+(?:\.\d*)?|\.\d+))\s*(deg|°|rad)?\s*$)",std::regex::icase);std::smatch match;if(!std::regex_match(value,match,pattern))return {{},"Enter an angle in degrees or radians"};double number=std::stod(match[1]);if(!std::isfinite(number))return {{},"Angle must be finite"};auto suffix=match[2].str();std::transform(suffix.begin(),suffix.end(),suffix.begin(),[](unsigned char c){return static_cast<char>(std::tolower(c));});if(suffix=="rad")return {number,{}};return {number*std::numbers::pi/180.0,{}};}catch(const std::exception& error){return {{},error.what()};}
}
bool routeSingleLetterShortcut(const KeyEvent& event){return !event.textInputFocused&&!event.control&&!event.alt&&event.key>0&&event.key<128&&std::isalpha(event.key);}
}
