#include "editor/plan_viewport.h"
#include "editor/session.h"
#include <QApplication>
#include <QElapsedTimer>
#include <QFocusEvent>
#include <QImage>
#include <QKeyEvent>
#include <QMouseEvent>
#include <QOpenGLWidget>
#include <QPainter>
#include <QPainterPath>
#include <QVBoxLayout>
#include <QWheelEvent>
#include <algorithm>
#include <cmath>
#include <numbers>

namespace kalara::editor {
namespace {
QColor color(render::Color value){return {value.r,value.g,value.b,value.a};}
render::SizeDip toDipSize(const QSizeF& value){return {value.width(),value.height()};}
PointerButton button(Qt::MouseButton value){if(value==Qt::LeftButton)return PointerButton::left;if(value==Qt::MiddleButton)return PointerButton::middle;if(value==Qt::RightButton)return PointerButton::right;return PointerButton::none;}
PointerEvent pointer(const QMouseEvent& event,const render::Camera2D& camera,const QSize& widgetSize){geometry::Point2 dip(event.position().x(),event.position().y());return {dip,camera.dipToWorld(dip,toDipSize(QSizeF(widgetSize))),button(event.button()),event.modifiers().testFlag(Qt::ShiftModifier),event.modifiers().testFlag(Qt::AltModifier),false};}
KeyEvent key(const QKeyEvent& event,bool pressed){return {event.key(),event.modifiers().testFlag(Qt::ShiftModifier),event.modifiers().testFlag(Qt::ControlModifier),event.modifiers().testFlag(Qt::AltModifier),false,pressed};}
QColor sceneColor(render::Color value,const QPalette& palette){
    if(value==render::Color{32,40,51,255}&&palette.color(QPalette::Base).lightness()<128)return palette.color(QPalette::Text);
    return color(value);
}
}
class PlanViewport::Canvas : public QWidget {
public:
    Canvas(PlanViewport& owner,QWidget* parent):QWidget(parent),owner_(owner){setMouseTracking(true);setFocusPolicy(Qt::StrongFocus);setAccessibleName("2D plan viewport");}
protected:
    void paintEvent(QPaintEvent*)override{QElapsedTimer timer;timer.start();QPainter painter(this);owner_.draw(painter,QSizeF(size()));owner_.record(timer.nsecsElapsed()/1000000.0);}
    void wheelEvent(QWheelEvent* event)override{const double steps=event->angleDelta().y()/120.0;owner_.camera_.zoomAt({event->position().x(),event->position().y()},std::pow(1.2,steps),toDipSize(QSizeF(this->size())));update();emit owner_.cameraChanged();event->accept();}
    void mousePressEvent(QMouseEvent* event)override{if(event->button()==Qt::MiddleButton||(event->button()==Qt::LeftButton&&owner_.spaceHeld_)){panning_=true;last_=event->position();setCursor(Qt::ClosedHandCursor);event->accept();return;}owner_.pointerDown(pointer(*event,owner_.camera_,size()));event->accept();}
    void mouseMoveEvent(QMouseEvent* event)override{if(panning_){const auto delta=event->position()-last_;last_=event->position();owner_.camera_.panDip({delta.x(),delta.y()});update();emit owner_.cameraChanged();event->accept();return;}owner_.pointerMove(pointer(*event,owner_.camera_,size()));event->accept();}
    void mouseReleaseEvent(QMouseEvent* event)override{if(panning_&&(event->button()==Qt::MiddleButton||event->button()==Qt::LeftButton)){panning_=false;unsetCursor();event->accept();return;}owner_.pointerUp(pointer(*event,owner_.camera_,size()));event->accept();}
    void keyPressEvent(QKeyEvent* event)override{owner_.keyInput(key(*event,true));event->accept();}void keyReleaseEvent(QKeyEvent* event)override{owner_.keyInput(key(*event,false));event->accept();}void focusOutEvent(QFocusEvent* event)override{owner_.cancelInteraction();QWidget::focusOutEvent(event);}
    PlanViewport& owner_;bool panning_=false;QPointF last_;
};
class GlCanvas final : public QOpenGLWidget {
public:
    GlCanvas(PlanViewport& owner,QWidget* parent):QOpenGLWidget(parent),owner_(owner){setMouseTracking(true);setFocusPolicy(Qt::StrongFocus);setAccessibleName("GPU 2D plan viewport");}
protected:
    void paintGL()override{QElapsedTimer timer;timer.start();QPainter painter(this);owner_.draw(painter,QSizeF(size()));owner_.record(timer.nsecsElapsed()/1000000.0);}
    void wheelEvent(QWheelEvent* event)override{const double steps=event->angleDelta().y()/120.0;owner_.camera().zoomAt({event->position().x(),event->position().y()},std::pow(1.2,steps),toDipSize(QSizeF(this->size())));update();emit owner_.cameraChanged();event->accept();}
    void mousePressEvent(QMouseEvent* event)override{if(event->button()==Qt::MiddleButton||(event->button()==Qt::LeftButton&&owner_.spaceHeld_)){panning_=true;last_=event->position();setCursor(Qt::ClosedHandCursor);event->accept();return;}owner_.pointerDown(pointer(*event,owner_.camera(),size()));event->accept();}
    void mouseMoveEvent(QMouseEvent* event)override{if(panning_){const auto delta=event->position()-last_;last_=event->position();owner_.camera().panDip({delta.x(),delta.y()});update();emit owner_.cameraChanged();event->accept();return;}owner_.pointerMove(pointer(*event,owner_.camera(),size()));event->accept();}
    void mouseReleaseEvent(QMouseEvent* event)override{if(panning_&&(event->button()==Qt::MiddleButton||event->button()==Qt::LeftButton)){panning_=false;unsetCursor();event->accept();return;}owner_.pointerUp(pointer(*event,owner_.camera(),size()));event->accept();}
    void keyPressEvent(QKeyEvent* event)override{owner_.keyInput(key(*event,true));event->accept();}void keyReleaseEvent(QKeyEvent* event)override{owner_.keyInput(key(*event,false));event->accept();}void focusOutEvent(QFocusEvent* event)override{owner_.cancelInteraction();QOpenGLWidget::focusOutEvent(event);}
private:
    PlanViewport& owner_;bool panning_=false;QPointF last_;
};
PlanViewport::PlanViewport(QWidget* parent,RendererMode mode):QWidget(parent),frames_(7200){setObjectName("planViewport");auto* layout=new QVBoxLayout(this);layout->setContentsMargins(0,0,0,0);rebuildCanvas(mode);}
void PlanViewport::rebuildCanvas(RendererMode requested){
    if(canvas_){layout()->removeWidget(canvas_);delete canvas_;canvas_=nullptr;}
    const bool offscreen=QApplication::platformName()=="offscreen"||QApplication::platformName()=="minimal";
    activeMode_=requested==RendererMode::automatic?(offscreen?RendererMode::painter:RendererMode::gpu):requested;
    canvas_=activeMode_==RendererMode::gpu?static_cast<QWidget*>(new GlCanvas(*this,this)):static_cast<QWidget*>(new Canvas(*this,this));
    layout()->addWidget(canvas_);canvas_->show();
}
void PlanViewport::setRendererMode(RendererMode mode){rebuildCanvas(mode);canvas_->update();emit cameraChanged();}
void PlanViewport::toggleSnap(){snapOptions_.enabled=!snapOptions_.enabled;if(!snapOptions_.enabled){snaps_.clear();snap_.reset();}canvas_->update();emit inputSettingsChanged();}
void PlanViewport::toggleOrtho(){snapOptions_.ortho=!snapOptions_.ortho;canvas_->update();emit inputSettingsChanged();}
void PlanViewport::toggleGrid(){snapOptions_.grid=!snapOptions_.grid;canvas_->update();emit inputSettingsChanged();}
void PlanViewport::setScene(render::Scene2D scene){scene_=std::move(scene);canvas_->update();}
void PlanViewport::refreshScene(){if(!session_)return;const render::SceneBuilder builder;setScene(builder.build(*session_->projectStore().snapshot(),{{{-10000000,-10000000},{10000000,10000000}},session_->activeFloorId()}));}
void PlanViewport::activateSelectTool(){wallMode_=false;openingMode_=false;wallAnchor_.reset();wallPreview_.reset();openingHost_.reset();cancelInteraction();canvas_->setFocus();}
void PlanViewport::activateWallTool(){cancelInteraction();openingMode_=false;openingHost_.reset();wallMode_=true;wallAnchor_.reset();wallPreview_.reset();canvas_->setFocus();}
void PlanViewport::activateOpeningTool(architecture::OpeningSpec spec){cancelInteraction();wallMode_=false;openingMode_=true;openingSpec_=std::move(spec);openingHost_.reset();openingFits_=false;canvas_->setFocus();}
std::string PlanViewport::commitWallNumeric(std::string_view input){if(!session_||!wallMode_||!wallAnchor_||!wallPreview_)return "Anchor a wall and point in its direction first";std::string text(input);geometry::Point2 endpoint;const auto comma=text.find(',');if(comma!=std::string::npos){const bool relative=!text.empty()&&text.front()=='@';const auto x=parseNumeric(std::string_view(text).substr(relative?1:0,comma-(relative?1:0)),relative?NumericField::deltaX:NumericField::absoluteX);const auto y=parseNumeric(std::string_view(text).substr(comma+1),relative?NumericField::deltaY:NumericField::absoluteY);if(!x.canonicalValue||!y.canonicalValue)return x.error.empty()?y.error:x.error;endpoint=relative?wallAnchor_->position+geometry::Vector2{*x.canonicalValue,*y.canonicalValue}:geometry::Point2{*x.canonicalValue,*y.canonicalValue};}else{const auto value=parseNumeric(text,NumericField::length);if(!value.canonicalValue||*value.canonicalValue<=0)return value.error.empty()?"Length must be positive":value.error;const auto delta=*wallPreview_-wallAnchor_->position;const auto length=geometry::norm(delta);if(length<=geometry::epsilon(length))return "Point in the segment direction first";endpoint=wallAnchor_->position+delta*(*value.canonicalValue/length);}auto result=session_->walls().addSegment(session_->activeFloorId(),session_->wallLayerId(),*wallAnchor_,{endpoint,{}});if(const auto* failure=std::get_if<runtime::CommitFailure>(&result))return failure->diagnostics.empty()?"Wall command failed":failure->diagnostics.front().message;refreshScene();wallAnchor_=architecture::WallEndpoint{endpoint,session_->walls().lastEndJunction()};wallPreview_=endpoint;return{};}
void PlanViewport::fitScene(){if(scene_.bounds)camera_.fit(*scene_.bounds,toDipSize(QSizeF(canvas_->size())));canvas_->update();emit cameraChanged();}
void PlanViewport::record(double milliseconds){frames_.record(milliseconds);emit frameRecorded(milliseconds);}
std::optional<architecture::EntityId> PlanViewport::snappedJunction()const{if(!snap_||snap_->stableKey.rfind("junction:",0)!=0)return{};return architecture::EntityId(snap_->stableKey.substr(9));}
void PlanViewport::pointerDown(const PointerEvent& event){if(!session_||event.button!=PointerButton::left)return;if(wallMode_||openingMode_)return;const auto snapshot=session_->projectStore().snapshot();for(const auto& selectedId:session_->selection())if(const auto* selected=snapshot->find(selectedId))if(const auto* opening=std::get_if<architecture::Opening>(selected)){const auto& wall=std::get<architecture::Wall>(*snapshot->find(opening->hostWallId));const auto a=std::get<architecture::Junction>(*snapshot->find(wall.startJunctionId)).position,b=std::get<architecture::Junction>(*snapshot->find(wall.endJunctionId)).position;const auto unit=(b-a)*(1/geometry::distance(a,b).mm);for(const int side:{-1,1}){const auto grip=a+unit*(opening->centerOffset.mm+side*opening->width.mm/2);const auto dip=camera_.worldToDip(grip,toDipSize(QSizeF(canvas_->size())));if(geometry::distance(dip,event.dip).mm<=8){movingId_=selectedId;openingDraftOffset_=opening->centerOffset;openingDraftWidth_=opening->width;openingResizeSide_=side;moveStartWorld_=event.world;moveDelta_={};session_->tools().pointerDown(event);canvas_->update();return;}}}auto hits=selectionQuery_.hitTest(*snapshot,camera_,toDipSize(QSizeF(canvas_->size())),event.dip,session_->selection());if(!hits.empty()&&session_->selection().contains(hits.front().id)&&selectionQuery_.movable(*snapshot,hits.front().id)){movingId_=hits.front().id;moveStartWorld_=event.world;moveDelta_={};if(const auto* opening=std::get_if<architecture::Opening>(snapshot->find(hits.front().id))){openingDraftOffset_=opening->centerOffset;openingDraftWidth_=opening->width;openingResizeSide_=0;}session_->tools().pointerDown(event);canvas_->update();return;}selecting_=true;selectionStartDip_=selectionCurrentDip_=event.dip;session_->tools().pointerDown(event);canvas_->update();}
void PlanViewport::pointerMove(const PointerEvent& event){if(session_)session_->tools().pointerMove(event);if(movingId_){moveDelta_=event.world-moveStartWorld_;const auto snapshot=session_->projectStore().snapshot();if(const auto* value=snapshot->find(*movingId_))if(const auto* opening=std::get_if<architecture::Opening>(value)){const auto& wall=std::get<architecture::Wall>(*snapshot->find(opening->hostWallId));const auto a=std::get<architecture::Junction>(*snapshot->find(wall.startJunctionId)).position,b=std::get<architecture::Junction>(*snapshot->find(wall.endJunctionId)).position;const auto axis=b-a;const double length=geometry::norm(axis),projected=std::clamp(geometry::dot(event.world-a,axis)/geometry::dot(axis,axis),0.0,1.0)*length;if(openingResizeSide_==0)openingDraftOffset_=geometry::Length(projected);else{const double fixed=opening->centerOffset.mm-openingResizeSide_*opening->width.mm/2;openingDraftWidth_=geometry::Length(std::abs(projected-fixed));openingDraftOffset_=geometry::Length((projected+fixed)/2);}}}if(selecting_)selectionCurrentDip_=event.dip;if(session_)snap_=snaps_.resolve(*session_->projectStore().snapshot(),camera_,toDipSize(QSizeF(canvas_->size())),event.dip,snapOptions_);if(wallMode_)wallPreview_=snap_?snap_->world:event.world;if(openingMode_&&session_){openingHost_.reset();openingFits_=false;double best=14;const auto snapshot=session_->projectStore().snapshot();for(const auto& [id,value]:snapshot->entities)if(const auto* wall=std::get_if<architecture::Wall>(&value);wall&&wall->floorId==session_->activeFloorId()){const auto a=std::get<architecture::Junction>(*snapshot->find(wall->startJunctionId)).position,b=std::get<architecture::Junction>(*snapshot->find(wall->endJunctionId)).position;const auto da=camera_.worldToDip(a,toDipSize(QSizeF(canvas_->size()))),db=camera_.worldToDip(b,toDipSize(QSizeF(canvas_->size())));const auto nearest=geometry::nearestPoint(event.dip,{da,db});const double distance=geometry::distance(nearest,event.dip).mm;if(distance>=best)continue;best=distance;openingHost_=id;openingOffset_=geometry::Length(geometry::distance(a,geometry::nearestPoint(event.world,{a,b})).mm);const double length=geometry::distance(a,b).mm,lo=openingOffset_.mm-openingSpec_.width.mm/2,hi=openingOffset_.mm+openingSpec_.width.mm/2;openingFits_=lo>=0&&hi<=length;for(const auto& [otherId,otherValue]:snapshot->entities)if(const auto* other=std::get_if<architecture::Opening>(&otherValue);other&&other->hostWallId==id){const double otherLo=other->centerOffset.mm-other->width.mm/2,otherHi=other->centerOffset.mm+other->width.mm/2;if(lo<otherHi&&hi>otherLo)openingFits_=false;}}}canvas_->update();}
void PlanViewport::pointerUp(const PointerEvent& event){if(!session_||event.button!=PointerButton::left)return;if(openingMode_){if(openingHost_&&openingFits_){auto result=session_->walls().placeOpening(*openingHost_,openingOffset_,openingSpec_);if(std::holds_alternative<runtime::CommitSuccess>(result))refreshScene();}canvas_->update();return;}if(wallMode_){const auto point=snap_?snap_->world:event.world;const auto junction=snappedJunction();if(!wallAnchor_){wallAnchor_=architecture::WallEndpoint{point,junction};wallPreview_=point;canvas_->update();return;}if(!geometry::near(wallAnchor_->position,point,geometry::distance(wallAnchor_->position,point).mm)){auto result=session_->walls().addSegment(session_->activeFloorId(),session_->wallLayerId(),*wallAnchor_,{point,junction});if(std::holds_alternative<runtime::CommitSuccess>(result)){refreshScene();wallAnchor_=architecture::WallEndpoint{point,session_->walls().lastEndJunction()};}}canvas_->update();return;}session_->tools().pointerUp(event);if(movingId_){if(geometry::norm(moveDelta_)>geometry::epsilon(geometry::norm(moveDelta_))){const auto* entity=session_->projectStore().snapshot()->find(*movingId_);if(entity){runtime::CommitResult result=std::holds_alternative<architecture::Wall>(*entity)?session_->walls().translateWall(*movingId_,moveDelta_):std::holds_alternative<architecture::Junction>(*entity)?session_->walls().moveJunction(*movingId_,moveStartWorld_+moveDelta_):std::holds_alternative<architecture::Opening>(*entity)?session_->walls().editOpening(*movingId_,openingDraftOffset_,openingDraftWidth_):runtime::CommitFailure{};if(std::holds_alternative<runtime::CommitSuccess>(result))refreshScene();}}movingId_.reset();openingResizeSide_=0;moveDelta_={};canvas_->update();return;}if(!selecting_)return;selectionCurrentDip_=event.dip;auto selected=session_->selection();const double movement=std::hypot(selectionCurrentDip_.x-selectionStartDip_.x,selectionCurrentDip_.y-selectionStartDip_.y);if(movement<4){auto hits=selectionQuery_.hitTest(*session_->projectStore().snapshot(),camera_,toDipSize(QSizeF(canvas_->size())),event.dip,selected);if(!event.alt)hitCycle_=0;auto hit=selectionQuery_.cycle(hits,event.alt?hitCycle_++:0);if(!event.shift)selected.clear();if(hit){if(event.shift&&selected.contains(hit->id))selected.erase(hit->id);else selected.insert(hit->id);}}else{auto found=selectionQuery_.marquee(*session_->projectStore().snapshot(),camera_,toDipSize(QSizeF(canvas_->size())),selectionStartDip_,selectionCurrentDip_);if(!event.shift)selected=std::move(found);else for(const auto& id:found){if(selected.contains(id))selected.erase(id);else selected.insert(id);}}session_->select(std::move(selected));selecting_=false;canvas_->update();}
void PlanViewport::keyInput(const KeyEvent& event){if(event.key==Qt::Key_Space){spaceHeld_=event.pressed;return;}if(!event.pressed)return;if(event.key==Qt::Key_Escape){wallAnchor_.reset();wallPreview_.reset();cancelInteraction();return;}if(event.key==Qt::Key_Tab)snap_=snaps_.cycle();else if(routeSingleLetterShortcut(event)&&event.key==Qt::Key_V)emit actionRequested("tool.select");else if(routeSingleLetterShortcut(event)&&event.key==Qt::Key_W)emit actionRequested("tool.wall");if(session_)session_->tools().key(event);canvas_->update();}
void PlanViewport::cancelInteraction(){selecting_=false;movingId_.reset();openingResizeSide_=0;openingHost_.reset();openingFits_=false;moveDelta_={};spaceHeld_=false;snap_.reset();snaps_.clear();if(session_)session_->tools().cancel();if(canvas_)canvas_->update();}
void PlanViewport::draw(QPainter& painter,const QSizeF& dipSize)const{
    painter.setRenderHint(QPainter::Antialiasing,true);painter.fillRect(QRectF(QPointF(0,0),dipSize),palette().color(QPalette::Base));const auto viewport=toDipSize(dipSize);
    const auto visible=camera_.visibleWorld(viewport);double grid=10;while(grid*camera_.pixelsPerMm<24)grid*=5;while(grid*camera_.pixelsPerMm>120)grid/=2;
    const bool dark=palette().color(QPalette::Base).lightness()<128;const QColor minorColor=dark?QColor("#394352"):QColor("#D9DFE7");const QColor majorColor=dark?QColor("#526075"):QColor("#BCC6D3");
    const auto x0=std::floor(visible.min.x/grid)*grid,y0=std::floor(visible.min.y/grid)*grid;
    for(double x=x0;x<=visible.max.x;x+=grid){const auto index=static_cast<long long>(std::llround(x/grid));painter.setPen(QPen(index%5?minorColor:majorColor,1));auto a=camera_.worldToDip({x,visible.min.y},viewport),b=camera_.worldToDip({x,visible.max.y},viewport);painter.drawLine(QPointF(a.x,a.y),QPointF(b.x,b.y));}
    for(double y=y0;y<=visible.max.y;y+=grid){const auto index=static_cast<long long>(std::llround(y/grid));painter.setPen(QPen(index%5?minorColor:majorColor,1));auto a=camera_.worldToDip({visible.min.x,y},viewport),b=camera_.worldToDip({visible.max.x,y},viewport);painter.drawLine(QPointF(a.x,a.y),QPointF(b.x,b.y));}
    for(const auto& fill:scene_.fills){QPolygonF polygon;for(auto p:fill.polygon.outer){auto dip=camera_.worldToDip(p,viewport);polygon<<QPointF(dip.x,dip.y);}QPainterPath path;path.addPolygon(polygon);for(const auto& hole:fill.polygon.holes){QPolygonF points;for(auto p:hole){auto dip=camera_.worldToDip(p,viewport);points<<QPointF(dip.x,dip.y);}QPainterPath holePath;holePath.addPolygon(points);path=path.subtracted(holePath);}painter.fillPath(path,color(fill.color));}
    for(const auto& line:scene_.lines){auto a=camera_.worldToDip(line.a,viewport),b=camera_.worldToDip(line.b,viewport);const bool selected=session_&&line.sourceId&&session_->selection().contains(*line.sourceId);QPen pen(selected?QColor("#2563EB"):sceneColor(line.color,palette()));pen.setWidthF(std::max(selected?2.0:1.0,line.widthMm*camera_.pixelsPerMm));painter.setPen(pen);painter.drawLine(QPointF(a.x,a.y),QPointF(b.x,b.y));}
    for(const auto& text:scene_.texts){auto p=camera_.worldToDip(text.anchor,viewport);QFont font=painter.font();font.setPixelSize(std::max(12,static_cast<int>(std::round(text.heightMm*camera_.pixelsPerMm))));painter.setFont(font);painter.setPen(sceneColor(text.color,palette()));painter.drawText(QPointF(p.x,p.y),QString::fromUtf8(text.text));}
    if(wallMode_&&wallAnchor_&&wallPreview_){const auto a=camera_.worldToDip(wallAnchor_->position,viewport),b=camera_.worldToDip(*wallPreview_,viewport);painter.setPen(QPen(QColor("#2563EB"),2,Qt::DashLine));painter.drawLine(QPointF(a.x,a.y),QPointF(b.x,b.y));const auto delta=*wallPreview_-wallAnchor_->position;const auto length=geometry::norm(delta),angle=std::atan2(delta.y,delta.x)*180/std::numbers::pi;painter.drawText(QPointF((a.x+b.x)/2+8,(a.y+b.y)/2-8),QString("%1 mm · %2°").arg(length,0,'f',1).arg(angle,0,'f',1));}
    if(openingMode_&&openingHost_&&session_){const auto snapshot=session_->projectStore().snapshot();const auto& wall=std::get<architecture::Wall>(*snapshot->find(*openingHost_));const auto start=std::get<architecture::Junction>(*snapshot->find(wall.startJunctionId)).position,end=std::get<architecture::Junction>(*snapshot->find(wall.endJunctionId)).position;const auto axis=end-start;const auto length=geometry::norm(axis);if(length>geometry::epsilon(length)){const auto tangent=axis*(1/length);const geometry::Vector2 side{-tangent.y,tangent.x};const auto center=start+tangent*openingOffset_.mm,a=center+tangent*(-openingSpec_.width.mm/2),b=center+tangent*(openingSpec_.width.mm/2);const auto a1=camera_.worldToDip(a+side*(-wall.thickness.mm/2),viewport),a2=camera_.worldToDip(a+side*(wall.thickness.mm/2),viewport),b1=camera_.worldToDip(b+side*(-wall.thickness.mm/2),viewport),b2=camera_.worldToDip(b+side*(wall.thickness.mm/2),viewport);const QColor preview=openingFits_?QColor("#16A34A"):QColor("#DC2626");painter.setPen(QPen(preview,3,Qt::DashLine));painter.drawLine(QPointF(a1.x,a1.y),QPointF(a2.x,a2.y));painter.drawLine(QPointF(b1.x,b1.y),QPointF(b2.x,b2.y));painter.drawLine(QPointF(a1.x,a1.y),QPointF(b1.x,b1.y));painter.drawLine(QPointF(a2.x,a2.y),QPointF(b2.x,b2.y));const auto label=camera_.worldToDip(center,viewport);painter.drawText(QPointF(label.x+10,label.y-12),openingFits_?QString("Fits · %1 mm").arg(openingSpec_.width.mm,0,'f',0):QString("Does not fit"));}}
    if(movingId_&&session_){const auto snapshot=session_->projectStore().snapshot();const auto* entity=snapshot->find(*movingId_);painter.setPen(QPen(QColor("#2563EB"),2,Qt::DashLine));if(entity)if(const auto* selectedWall=std::get_if<architecture::Wall>(entity)){const auto a=std::get<architecture::Junction>(*snapshot->find(selectedWall->startJunctionId)).position+moveDelta_,b=std::get<architecture::Junction>(*snapshot->find(selectedWall->endJunctionId)).position+moveDelta_;const auto da=camera_.worldToDip(a,viewport),db=camera_.worldToDip(b,viewport);painter.drawLine(QPointF(da.x,da.y),QPointF(db.x,db.y));}else if(const auto* junction=std::get_if<architecture::Junction>(entity))for(const auto& [id,value]:snapshot->entities)if(const auto* incidentWall=std::get_if<architecture::Wall>(&value);incidentWall&&(incidentWall->startJunctionId==junction->header.id||incidentWall->endJunctionId==junction->header.id)){auto a=std::get<architecture::Junction>(*snapshot->find(incidentWall->startJunctionId)).position,b=std::get<architecture::Junction>(*snapshot->find(incidentWall->endJunctionId)).position;if(incidentWall->startJunctionId==junction->header.id)a=a+moveDelta_;else b=b+moveDelta_;const auto da=camera_.worldToDip(a,viewport),db=camera_.worldToDip(b,viewport);painter.drawLine(QPointF(da.x,da.y),QPointF(db.x,db.y));}}
    if(session_&&session_->selection().size()==1){const auto id=*session_->selection().begin();const auto snapshot=session_->projectStore().snapshot();if(const auto* value=snapshot->find(id))if(const auto* opening=std::get_if<architecture::Opening>(value)){const auto& wall=std::get<architecture::Wall>(*snapshot->find(opening->hostWallId));const auto start=std::get<architecture::Junction>(*snapshot->find(wall.startJunctionId)).position,end=std::get<architecture::Junction>(*snapshot->find(wall.endJunctionId)).position;const auto axis=end-start;const double length=geometry::norm(axis);if(length>geometry::epsilon(length)){const auto unit=axis*(1/length);const double offset=movingId_&&*movingId_==id?openingDraftOffset_.mm:opening->centerOffset.mm,width=movingId_&&*movingId_==id?openingDraftWidth_.mm:opening->width.mm;const auto center=start+unit*offset,a=center+unit*(-width/2),b=center+unit*(width/2);const auto da=camera_.worldToDip(a,viewport),db=camera_.worldToDip(b,viewport),dc=camera_.worldToDip(center,viewport);painter.setPen(QPen(QColor("#2563EB"),2,Qt::DashLine));painter.drawLine(QPointF(da.x,da.y),QPointF(db.x,db.y));painter.setBrush(QColor("#FFFFFF"));painter.drawEllipse(QPointF(da.x,da.y),5,5);painter.drawEllipse(QPointF(db.x,db.y),5,5);painter.setBrush(QColor("#2563EB"));painter.drawEllipse(QPointF(dc.x,dc.y),4,4);}}}
    if(selecting_){QPen pen(QColor("#2563EB"),1,selectionCurrentDip_.x<selectionStartDip_.x?Qt::DashLine:Qt::SolidLine);painter.setPen(pen);painter.setBrush(QColor(37,99,235,28));painter.drawRect(QRectF(QPointF(selectionStartDip_.x,selectionStartDip_.y),QPointF(selectionCurrentDip_.x,selectionCurrentDip_.y)).normalized());}
    if(snap_){const auto p=camera_.worldToDip(snap_->world,viewport);painter.setPen(QPen(QColor("#2563EB"),2));painter.setBrush(Qt::NoBrush);painter.drawEllipse(QPointF(p.x,p.y),5,5);painter.drawText(QPointF(p.x+9,p.y-9),QString::fromStdString(snap_->label));}
}
QImage PlanViewport::renderImage(QSize dipSize,qreal dpr)const{QImage image(dipSize*dpr,QImage::Format_ARGB32_Premultiplied);image.setDevicePixelRatio(dpr);QPainter painter(&image);draw(painter,QSizeF(dipSize));return image;}
}
