#include "render/scene.h"
#include <algorithm>
#include <cmath>
#include <limits>
#include <numbers>
namespace kalara::render {
namespace {
bool overlaps(geometry::AABB2 a,geometry::AABB2 b){return a.min.x<=b.max.x&&a.max.x>=b.min.x&&a.min.y<=b.max.y&&a.max.y>=b.min.y;}
geometry::AABB2 box(geometry::Point2 a,geometry::Point2 b,double pad){return {{std::min(a.x,b.x)-pad,std::min(a.y,b.y)-pad},{std::max(a.x,b.x)+pad,std::max(a.y,b.y)+pad}};}
void expand(std::optional<geometry::AABB2>& bounds,geometry::Point2 p){if(!bounds){bounds=geometry::AABB2{p,p};return;}bounds->min.x=std::min(bounds->min.x,p.x);bounds->min.y=std::min(bounds->min.y,p.y);bounds->max.x=std::max(bounds->max.x,p.x);bounds->max.y=std::max(bounds->max.y,p.y);}
struct WallShape{architecture::EntityId id;geometry::Polygon2 polygon;};
bool filled(geometry::Point2 point,const std::vector<WallShape>& shapes){for(const auto& shape:shapes)if(geometry::locate(point,shape.polygon)!=geometry::Location::outside)return true;return false;}
double endpointExtension(const architecture::Project& project,const architecture::Wall& wall,const architecture::EntityId& junctionId){std::vector<geometry::Vector2> rays;double largest=wall.thickness.mm;const auto joint=std::get<architecture::Junction>(*project.find(junctionId)).position;for(const auto& [id,value]:project.entities)if(const auto* candidate=std::get_if<architecture::Wall>(&value);candidate&&candidate->floorId==wall.floorId&&(candidate->startJunctionId==junctionId||candidate->endJunctionId==junctionId)){const auto otherId=candidate->startJunctionId==junctionId?candidate->endJunctionId:candidate->startJunctionId;const auto other=std::get<architecture::Junction>(*project.find(otherId)).position;const auto vector=other-joint;const auto length=geometry::norm(vector);if(length>geometry::epsilon(length))rays.push_back(vector*(1/length));largest=std::max(largest,candidate->thickness.mm);}if(rays.size()<2)return 0;if(rays.size()>2)return largest/2;const double cosine=std::clamp(geometry::dot(rays[0],rays[1]),-1.0,1.0),angle=std::acos(cosine);if(angle<=1e-8)return 4*largest;return std::min(4*largest,(largest/2)/std::tan(angle/2));}
}
Scene2D SceneBuilder::build(const architecture::Project& snapshot,const ViewSpec& view)const{
    Scene2D scene;std::vector<WallShape> shapes;
    SceneIndex index;index.rebuild(snapshot);
    for(const auto& id:index.query(view.worldBounds,view.floorId)){const auto& value=*snapshot.find(id);const auto* wall=std::get_if<architecture::Wall>(&value);if(!wall)continue;
        const auto* startValue=snapshot.find(wall->startJunctionId);const auto* endValue=snapshot.find(wall->endJunctionId);if(!startValue||!endValue)continue;
        const auto start=std::get<architecture::Junction>(*startValue).position,end=std::get<architecture::Junction>(*endValue).position;
        if(!overlaps(box(start,end,wall->thickness.mm/2),view.worldBounds))continue;
        const auto direction=end-start;const auto length=geometry::norm(direction);const auto unit=direction*(1/length);const geometry::Vector2 normal{-unit.y*wall->thickness.mm/2,unit.x*wall->thickness.mm/2};const double startExtension=endpointExtension(snapshot,*wall,wall->startJunctionId),endExtension=endpointExtension(snapshot,*wall,wall->endJunctionId);
        std::vector<const architecture::Opening*> openings;for(const auto& [openingId,entity]:snapshot.entities)if(const auto* opening=std::get_if<architecture::Opening>(&entity);opening&&opening->hostWallId==id)openings.push_back(opening);std::sort(openings.begin(),openings.end(),[](const auto* a,const auto* b){return a->centerOffset.mm<b->centerOffset.mm;});
        auto addWallPiece=[&](double from,double to){if(to-from<=geometry::epsilon(length))return;const auto a=start+unit*from,b=start+unit*to;geometry::Polygon2 polygon{{a+normal*-1,b+normal*-1,b+normal,a+normal},{}};scene.fills.push_back({polygon,{224,226,230,255},snapshot.revision,id});shapes.push_back({id,polygon});for(auto p:polygon.outer)expand(scene.bounds,p);};
        double cursor=-startExtension;for(const auto* opening:openings){const double lo=opening->centerOffset.mm-opening->width.mm/2,hi=opening->centerOffset.mm+opening->width.mm/2;addWallPiece(cursor,lo);cursor=hi;}addWallPiece(cursor,length+endExtension);
    }
    for(const auto& shape:shapes)for(std::size_t edgeIndex=0;edgeIndex<shape.polygon.outer.size();++edgeIndex){const geometry::Segment2 edge(shape.polygon.outer[edgeIndex],shape.polygon.outer[(edgeIndex+1)%shape.polygon.outer.size()]);std::vector<double> cuts{0,1};for(const auto& other:shapes)for(std::size_t j=0;j<other.polygon.outer.size();++j){const geometry::Segment2 otherEdge(other.polygon.outer[j],other.polygon.outer[(j+1)%other.polygon.outer.size()]);for(const auto point:geometry::intersections(edge,otherEdge)){const auto parameter=geometry::projectionParameter(point,edge);if(parameter>0&&parameter<1)cuts.push_back(parameter);}}std::sort(cuts.begin(),cuts.end());cuts.erase(std::unique(cuts.begin(),cuts.end(),[](double a,double b){return std::abs(a-b)<1e-10;}),cuts.end());const auto vector=edge.b-edge.a;const auto length=geometry::norm(vector);const geometry::Vector2 normal{-vector.y/length,vector.x/length};const double probe=std::max(geometry::epsilon(length)*10,1e-5);for(std::size_t i=1;i<cuts.size();++i){if(cuts[i]-cuts[i-1]<1e-10)continue;const auto a=edge.a+vector*cuts[i-1],b=edge.a+vector*cuts[i],middle=a+(b-a)*.5;if(filled(middle+normal*probe,shapes)==filled(middle+normal*-probe,shapes))continue;bool duplicate=false;for(const auto& line:scene.lines)if((geometry::near(line.a,a,length)&&geometry::near(line.b,b,length))||(geometry::near(line.a,b,length)&&geometry::near(line.b,a,length))){duplicate=true;break;}if(!duplicate)scene.lines.push_back({a,b,0.35,{32,40,51,255},snapshot.revision,shape.id});}}
    auto addSymbolLine=[&](geometry::Point2 a,geometry::Point2 b,const architecture::EntityId& id,double width=.35){scene.lines.push_back({a,b,width,{32,40,51,255},snapshot.revision,id});expand(scene.bounds,a);expand(scene.bounds,b);};
    for(const auto& [id,value]:snapshot.entities){const auto* opening=std::get_if<architecture::Opening>(&value);if(!opening||view.floorId&&opening->floorId!=*view.floorId)continue;const auto* hostValue=snapshot.find(opening->hostWallId);if(!hostValue)continue;const auto& wall=std::get<architecture::Wall>(*hostValue);const auto a=std::get<architecture::Junction>(*snapshot.find(wall.startJunctionId)).position,b=std::get<architecture::Junction>(*snapshot.find(wall.endJunctionId)).position;const auto axis=b-a;const double hostLength=geometry::norm(axis);if(hostLength<=geometry::epsilon(hostLength))continue;const auto tangent=axis*(1/hostLength);const geometry::Vector2 side{-tangent.y,tangent.x};const double halfWall=wall.thickness.mm/2,lo=opening->centerOffset.mm-opening->width.mm/2,hi=opening->centerOffset.mm+opening->width.mm/2;const auto jambA=a+tangent*lo,jambB=a+tangent*hi;addSymbolLine(jambA+side*(-halfWall),jambA+side*halfWall,id);addSymbolLine(jambB+side*(-halfWall),jambB+side*halfWall,id);
        if(opening->kind==architecture::OpeningKind::window){addSymbolLine(jambA+side*(-halfWall*.32),jambB+side*(-halfWall*.32),id);addSymbolLine(jambA+side*(halfWall*.32),jambB+side*(halfWall*.32),id);if(opening->windowPattern==architecture::WindowPattern::sliding){const auto middle=jambA+tangent*(opening->width.mm/2);addSymbolLine(middle+side*(-halfWall*.32),middle+side*(halfWall*.32),id);}continue;}
        if(opening->doorPattern==architecture::DoorPattern::openPassage)continue;if(opening->doorPattern==architecture::DoorPattern::sliding||opening->doorPattern==architecture::DoorPattern::pocket){const auto shift=side*(opening->swing==architecture::SwingSide::left?halfWall*.65:-halfWall*.65);addSymbolLine(jambA+shift,jambB+shift,id);addSymbolLine(jambA+shift+side*12,jambB+shift+side*12,id);continue;}
        const bool hingeAtStart=opening->hinge==architecture::HingeEnd::start;const auto hinge=hingeAtStart?jambA:jambB;const auto closed=(hingeAtStart?tangent:tangent*-1)*opening->width.mm;const double sign=opening->swing==architecture::SwingSide::left?1:-1;const geometry::Vector2 opened{-closed.y*sign,closed.x*sign};addSymbolLine(hinge,hinge+opened,id);geometry::Point2 previous=hinge+closed;constexpr int segments=12;for(int segment=1;segment<=segments;++segment){const double angle=sign*(std::numbers::pi/2)*(static_cast<double>(segment)/segments);const geometry::Vector2 rotated{closed.x*std::cos(angle)-closed.y*std::sin(angle),closed.x*std::sin(angle)+closed.y*std::cos(angle)};const auto next=hinge+rotated;addSymbolLine(previous,next,id,.2);previous=next;}if(opening->doorPattern==architecture::DoorPattern::doubleSwing){const auto other=hingeAtStart?jambB:jambA;addSymbolLine(other,other+opened*(-1),id);}
    }
    return scene;
}
void SceneIndex::rebuild(const architecture::Project& snapshot){entries_.clear();for(const auto& [id,value]:snapshot.entities){const auto* wall=std::get_if<architecture::Wall>(&value);if(!wall)continue;const auto* a=snapshot.find(wall->startJunctionId);const auto* b=snapshot.find(wall->endJunctionId);if(!a||!b)continue;entries_.push_back({id,wall->floorId,box(std::get<architecture::Junction>(*a).position,std::get<architecture::Junction>(*b).position,wall->thickness.mm/2)});}}
std::vector<architecture::EntityId> SceneIndex::query(geometry::AABB2 worldBounds,std::optional<architecture::EntityId> floorId)const{std::vector<architecture::EntityId> result;for(const auto& entry:entries_)if((!floorId||entry.floorId==*floorId)&&overlaps(entry.bounds,worldBounds))result.push_back(entry.id);return result;}
}
